# Cargue y Limpieza de los datos

In [85]:
!pip install pyreadstat

Requirement already satisfied: pyreadstat in c:\users\henry\miniconda3\envs\ml_venv\lib\site-packages (1.2.8)
Requirement already satisfied: pandas>=1.2.0 in c:\users\henry\miniconda3\envs\ml_venv\lib\site-packages (from pyreadstat) (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\henry\miniconda3\envs\ml_venv\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\henry\miniconda3\envs\ml_venv\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\henry\miniconda3\envs\ml_venv\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\henry\miniconda3\envs\ml_venv\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\henry\miniconda3\envs\ml_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadstat) (1.17.0)

In [86]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio

# Set the renderer explicitly
pio.renderers.default = 'notebook'

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pyreadstat
from IPython.core.display import display, HTML
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import json
import os
import requests
import plotly.io as pio
pio.renderers.default = "notebook"  # Para Jupyter Notebook
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix

C:\Users\henry\AppData\Local\Temp\ipykernel_9448\3854545128.py:10: DeprecationWarning:

Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display

## Preprocesamiento y cargue de los Datos

In [ ]:
data_path = 'C:/Users/henry/Documents/jbook/Cacervix/datos/'
data = pyreadstat.read_sav(data_path + 'CACU1985A2023.sav')
enfermedades = pd.read_excel(data_path + 'enfermedades.xlsx')
poblacion_mujeres = pd.read_excel(data_path + 'poblacion_mujeres.xlsx')

In [89]:
print(type(data))
data = data[0]

<class 'tuple'>

Se realiza el cargue adecuado de los datos a trabajar. El conjunto de datos consta de 61 variables y 58934 observaciones sobre las defunciones por cáncer de cuello uterino en el periodo 1985 a 2019. Muchas de ellas se encuentran codificadas por lo que se le debe brindar un tratamiento respectivo con un directorio medico oportuno.

In [90]:
display(HTML(data.head().to_html()))

In [91]:
data.shape

(58934, 61)

In [92]:
print(f'El conjunto de datos tiene {data.shape[0]} filas ')
print(f'El conjunto de datos tiene {data.shape[1]} columnas')

El conjunto de datos tiene 58934 filas
El conjunto de datos tiene 61 columnas

In [93]:
for col in data.columns:
    print(f'El tipo es: {data[col].dtype} y el nombre es: {col}')

El tipo es: object y el nombre es: COD_DPTO
El tipo es: object y el nombre es: COD_MUNIC
El tipo es: object y el nombre es: A_DEFUN
El tipo es: object y el nombre es: ANO
El tipo es: object y el nombre es: MES
El tipo es: object y el nombre es: SEXO
El tipo es: object y el nombre es: GRU_ED1
El tipo es: object y el nombre es: EST_CIVIL
El tipo es: object y el nombre es: CODPTORE
El tipo es: object y el nombre es: CODMUNRE
El tipo es: object y el nombre es: SIT_DEFUN
El tipo es: object y el nombre es: C_BAS1
El tipo es: object y el nombre es: CONS_EXP
El tipo es: object y el nombre es: CAU_HOMOL
El tipo es: object y el nombre es: NOMBRE_ARCHIVO
El tipo es: object y el nombre es: GRU_ED2
El tipo es: object y el nombre es: AREA_RES
El tipo es: object y el nombre es: perman_mun
El tipo es: object y el nombre es: PMAN_MUER
El tipo es: object y el nombre es: tiem_per
El tipo es: object y el nombre es: COD_INST
El tipo es: object y el nombre es: NOM_INST
El tipo es: object y el nombre es: NIVEL_EDU
El tipo es: object y el nombre es: CODPRES
El tipo es: object y el nombre es: SEG_SOCIAL
El tipo es: object y el nombre es: EST_CIVM
El tipo es: object y el nombre es: MAN_MUER
El tipo es: object y el nombre es: CODOCUR
El tipo es: object y el nombre es: CODMUNOC
El tipo es: object y el nombre es: C_MUERTE
El tipo es: object y el nombre es: ASIS_MED
El tipo es: object y el nombre es: C_DIR1
El tipo es: object y el nombre es: C_ANT1
El tipo es: object y el nombre es: C_ANT2
El tipo es: object y el nombre es: C_ANT3
El tipo es: object y el nombre es: C_PAT1
El tipo es: object y el nombre es: C_MCM1
El tipo es: object y el nombre es: CAUSA_666
El tipo es: object y el nombre es: OTRSITIODE
El tipo es: object y el nombre es: HORA
El tipo es: object y el nombre es: SIMUERTEPO
El tipo es: object y el nombre es: OCUPACION
El tipo es: object y el nombre es: IDPERTET
El tipo es: object y el nombre es: IDADMISALUD
El tipo es: object y el nombre es: IDCLASADMI
El tipo es: object y el nombre es: C_MUERTEB
El tipo es: object y el nombre es: C_MUERTEC
El tipo es: object y el nombre es: C_MUERTED
El tipo es: object y el nombre es: C_MUERTEE
El tipo es: object y el nombre es: C_DIR12
El tipo es: object y el nombre es: C_ANT12
El tipo es: object y el nombre es: C_ANT22
El tipo es: object y el nombre es: C_ANT32
El tipo es: object y el nombre es: C_PAT2
El tipo es: object y el nombre es: IDPROFCER
El tipo es: object y el nombre es: CAUSA_667
El tipo es: object y el nombre es: P_PMAN_IRIS
El tipo es: object y el nombre es: CAUSA_MULT
El tipo es: float64 y el nombre es: TIPOFORMULARIO
El tipo es: float64 y el nombre es: Year
El tipo es: float64 y el nombre es: filter_$

## Explicación de variables

- **COD_DPTO**: Departamento donde ocurrió la defunción  
- **COD_MUNIC**: Municipio donde ocurrió la defunción  
- **A_DEFUN**: Área donde ocurrió la defunción  
- **SIT_DEFUN**: Sitio de la defunción  
- **COD_INST**: Código de la institución prestadora de salud  
- **NOM_INST**: Nombre de la institución de salud  
- **ANO**: Año en que ocurrió la defunción  
- **MES**: Mes en que ocurrió la defunción  
- **SEXO**: Sexo del fallecido  
- **EST_CIVIL**: Estado conyugal del fallecido  
- **gru_ed1**: Agrupación de edades, según la edad del fallecido  
- **gru_ed2**: Agrupación alternativa de edades del fallecido  
- **NIVEL_EDU**: Nivel educativo alcanzado por el fallecido  
- **MUERTEPORO**: Ocupación como posible causa o factor asociado a la defunción  
- **SIMUERTEPO**: Si fue accidente de trabajo o enfermedad profesional  
- **OCUPACION**: Última ocupación habitual del fallecido  
- **IDPERTET**: Autoidentificación étnica del fallecido  
- **CODPRES**: País de residencia habitual si era diferente a Colombia  
- **CODPTORE**: Departamento de residencia habitual del fallecido  
- **CODMUNRE**: Municipio de residencia habitual del fallecido  
- **AREA_RES**: Área de residencia habitual del fallecido  
- **SEG_SOCIAL**: Régimen de seguridad social del fallecido  
- **IDADMISALU**: Entidad administradora en salud (o de la madre, si es muerte fetal o de menor de un año)  
- **IDCLASADMI**: Nombre de la administradora de salud  
- **pman_muer**: Probable manera de muerte  
- **CONS_EXP**: Certificación médica de la defunción  
- **CODOCUR**: Departamento de ocurrencia del hecho violento (si aplica)  
- **CODMUNOC**: Municipio de ocurrencia del hecho violento (si aplica)  
- **c_muerte**: Método de determinación de la causa de muerte  
- **ASIS_MED**: Si recibió asistencia médica antes de morir  
- **CAUSA_MULT**: Códigos de causas múltiples como antecedentes  
- **C_DIR1**: Causa directa de la defunción  
- **C_DIR12**: Segundo código informado para la causa directa  
- **C_ANT1**: Primera causa antecedente  
- **C_ANT12**: Segundo código informado para la causa antecedente 1  
- **C_ANT2**: Segunda causa antecedente  
- **C_ANT22**: Segundo código informado para la causa antecedente 2  
- **C_ANT3**: Tercera causa antecedente  
- **C_ANT32**: Segundo código informado para la causa antecedente 3  
- **C_PAT1**: Otros estados patológicos importantes  
- **C_PAT2**: Código correspondiente a C_PAT1  
- **C_BAS1**: Código de la causa básica de defunción  
- **C_MCM1**: Código de causa sin certificación médica  
- **IDPROFCER**: Profesión de quien certifica la defunción  
- **CAUSA_666_667**: Agrupación de causa según Lista 6/67 OPS  
- **CAU_HOMOL**: Agrupación de causa básica según Lista 105 Colombia  
- **QUINQ**: Quinquenio de edad del fallecido (variable agrupada en intervalos de 5 años)  
- **EDAD2**: Edad del fallecido en una unidad específica (días, meses o años, según contexto)

In [94]:
print(data.columns.tolist())

['COD_DPTO', 'COD_MUNIC', 'A_DEFUN', 'ANO', 'MES', 'SEXO', 'GRU_ED1', 'EST_CIVIL', 'CODPTORE', 'CODMUNRE', 'SIT_DEFUN', 'C_BAS1', 'CONS_EXP', 'CAU_HOMOL', 'NOMBRE_ARCHIVO', 'GRU_ED2', 'AREA_RES', 'perman_mun', 'PMAN_MUER', 'tiem_per', 'COD_INST', 'NOM_INST', 'NIVEL_EDU', 'CODPRES', 'SEG_SOCIAL', 'EST_CIVM', 'MAN_MUER', 'CODOCUR', 'CODMUNOC', 'C_MUERTE', 'ASIS_MED', 'C_DIR1', 'C_ANT1', 'C_ANT2', 'C_ANT3', 'C_PAT1', 'C_MCM1', 'CAUSA_666', 'OTRSITIODE', 'HORA', 'SIMUERTEPO', 'OCUPACION', 'IDPERTET', 'IDADMISALUD', 'IDCLASADMI', 'C_MUERTEB', 'C_MUERTEC', 'C_MUERTED', 'C_MUERTEE', 'C_DIR12', 'C_ANT12', 'C_ANT22', 'C_ANT32', 'C_PAT2', 'IDPROFCER', 'CAUSA_667', 'P_PMAN_IRIS', 'CAUSA_MULT', 'TIPOFORMULARIO', 'Year', 'filter_$']

## Análisis por departamento y municipio

Dado que las variables están codificadas a través de un número universal declarado por el departamento administrativo nacional de estadística (DANE). Se identificó inicalmente que valores únicos o conteos existían para cada departamento.

In [95]:
print(data['COD_DPTO'].unique())

['50' '15' '41' '25' '86' '81' '99' '18' '85' '95' '11' '8' '13' '47' '70'
 '88' '44' '20' '76' '19' '52' '5' '23' '27' '68' '54' '17' '63' '66' '73'
 '91' '94' '97']

Se mapea el codigo universal de cada departamento con su respectivo nombre y se tranasforma a string para poder crear una columna nueva con el nombre oficial del departamento.

In [96]:
map_dpto = {
    '5': 'ANTIOQUIA',
    '8': 'ATLÁNTICO',
    '11': 'BOGOTÁ, D.C.',
    '13': 'BOLÍVAR',
    '15': 'BOYACÁ',
    '17': 'CALDAS',
    '18': 'CAQUETÁ',
    '19': 'CAUCA',
    '20': 'CESAR',
    '23': 'CÓRDOBA',
    '25': 'CUNDINAMARCA',
    '27': 'CHOCÓ',
    '41': 'HUILA',
    '44': 'LA GUAJIRA',
    '47': 'MAGDALENA',
    '50': 'META',
    '52': 'NARIÑO',
    '54': 'NORTE DE SANTANDER',
    '63': 'QUINDÍO',
    '66': 'RISARALDA',
    '68': 'SANTANDER',
    '70': 'SUCRE',
    '73': 'TOLIMA',
    '76': 'VALLE DEL CAUCA',
    '81': 'ARAUCA',
    '85': 'CASANARE',
    '86': 'PUTUMAYO',
    '88': 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA',
    '91': 'AMAZONAS',
    '94': 'GUAINÍA',
    '95': 'GUAVIARE',
    '97': 'VAUPÉS',
    '99': 'VICHADA'
}
print('Los departamentos son: \n', map_dpto)

Los departamentos son:
 {'5': 'ANTIOQUIA', '8': 'ATLÁNTICO', '11': 'BOGOTÁ, D.C.', '13': 'BOLÍVAR', '15': 'BOYACÁ', '17': 'CALDAS', '18': 'CAQUETÁ', '19': 'CAUCA', '20': 'CESAR', '23': 'CÓRDOBA', '25': 'CUNDINAMARCA', '27': 'CHOCÓ', '41': 'HUILA', '44': 'LA GUAJIRA', '47': 'MAGDALENA', '50': 'META', '52': 'NARIÑO', '54': 'NORTE DE SANTANDER', '63': 'QUINDÍO', '66': 'RISARALDA', '68': 'SANTANDER', '70': 'SUCRE', '73': 'TOLIMA', '76': 'VALLE DEL CAUCA', '81': 'ARAUCA', '85': 'CASANARE', '86': 'PUTUMAYO', '88': 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', '91': 'AMAZONAS', '94': 'GUAINÍA', '95': 'GUAVIARE', '97': 'VAUPÉS', '99': 'VICHADA'}

In [97]:
tipo= data['COD_DPTO'].dtype
print('El tipo de datos es: ', tipo)
if data['COD_DPTO'].dtype == 'int64':
    data['COD_DPTO'] = data['COD_DPTO'].astype(str)
    print(f'Y dado que era {tipo} , se convirtió a string')
    data['DEPARTAMENTO'] = data['COD_DPTO'].map(map_dpto)
    print(data['DEPARTAMENTO'].unique())
else:
    data['DEPARTAMENTO'] = data['COD_DPTO'].map(map_dpto)
    print(data['DEPARTAMENTO'].unique())

El tipo de datos es:  object
['META' 'BOYACÁ' 'HUILA' 'CUNDINAMARCA' 'PUTUMAYO' 'ARAUCA' 'VICHADA'
 'CAQUETÁ' 'CASANARE' 'GUAVIARE' 'BOGOTÁ, D.C.' 'ATLÁNTICO' 'BOLÍVAR'
 'MAGDALENA' 'SUCRE'
 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA' 'LA GUAJIRA'
 'CESAR' 'VALLE DEL CAUCA' 'CAUCA' 'NARIÑO' 'ANTIOQUIA' 'CÓRDOBA' 'CHOCÓ'
 'SANTANDER' 'NORTE DE SANTANDER' 'CALDAS' 'QUINDÍO' 'RISARALDA' 'TOLIMA'
 'AMAZONAS' 'GUAINÍA' 'VAUPÉS']

In [98]:
print('Número de departamentos y/o ciudades:', len(data['DEPARTAMENTO'].unique()))

Número de departamentos y/o ciudades: 33

#### Mapear departamento habitual de residencia

In [99]:
tipo= data['CODPTORE'].dtype
print('El tipo de datos es: ', tipo)
if data['CODPTORE'].dtype == 'int64':
    data['CODPTORE'] = data['CODPTORE'].astype(str)
    print(f'Y dado que era {tipo} , se convirtió a string')
    data['DEPARTAMENTO DE RESIDENCIA'] = data['CODPTORE'].map(map_dpto)
    print(data['DEPARTAMENTO DE RESIDENCIA'].unique())
else:
    data['DEPARTAMENTO DE RESIDENCIA'] = data['CODPTORE'].map(map_dpto)
    print(data['DEPARTAMENTO DE RESIDENCIA'].unique())

El tipo de datos es:  object
['META' 'BOYACÁ' 'HUILA' 'CUNDINAMARCA' 'PUTUMAYO' 'ARAUCA' 'VICHADA' nan
 'CAQUETÁ' 'BOGOTÁ, D.C.' 'TOLIMA' 'CASANARE' 'GUAVIARE' 'SANTANDER'
 'CALDAS' 'BOLÍVAR' 'MAGDALENA' 'SUCRE'
 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA' 'LA GUAJIRA'
 'CESAR' 'VALLE DEL CAUCA' 'CAUCA' 'RISARALDA' 'NARIÑO' 'CÓRDOBA' 'CHOCÓ'
 'NORTE DE SANTANDER' 'QUINDÍO' 'AMAZONAS' 'GUAINÍA' 'VAUPÉS']

**Reorganizar columnas**

Posterior a mapear los nombres de cada departamento con su respectivo código se reorganizan las columnas al inicio del conjunto de datos.

In [100]:
columnas = ['COD_DPTO', 'DEPARTAMENTO', 'DEPARTAMENTO DE RESIDENCIA'] + [col for col in data.columns if col not in ['COD_DPTO', 'DEPARTAMENTO', 'DEPARTAMENTO DE RESIDENCIA']]
data = data[columnas]
display(HTML(data.head(10).to_html()))

Codificar municipios

Para decodificar los nombres de cada municipio, el proceso implicó varios pasos para garantizar la precisión de la asignación y el formato. Primero, se extrajeron los códigos únicos de los municipios y se cargó un diccionario con la asignación de los códigos de los municipios a sus respectivos nombres desde un archivo JSON. Posteriormente, se estandarizaron los códigos de los departamentos añadiendo ceros a la izquierda cuando fue necesario, y se formatearon para asegurar su consistencia. Se creó una nueva columna combinando los códigos de los departamentos estandarizados con los de los municipios para formar un código de municipio corregido. Este código corregido se asignó a los nombres de los municipios utilizando el diccionario cargado. Se identificaron y solucionaron los valores faltantes en los nombres de los municipios resultantes. Finalmente, se reorganizaron las columnas para incluir la información relevante, lo que hizo que el conjunto de datos fuera más interpretable y estuviera listo para su posterior análisis.

In [145]:
print(data['COD_MUNIC'].tolist())

['313', '001', '606', '001', '001', '013', '815', '175', '290', '298', '551', '551', '244', '006', '759', '322', '001', '001', '001', '313', '313', '006', '615', '668', '001', '001', '001', '001', '551', '794', '736', '001', '807', '001', '001', '875', '875', '480', '001', '001', '843', '001', '658', '740', '001', '001', '349', '317', '290', '307', '307', '815', '551', '486', '001', '001', '867', '297', '290', '290', '307', '568', '320', '120', '001', '298', '668', '676', '001', '001', '817', '851', '649', '841', '297', '753', '759', '010', '568', '006', '001', '402', '183', '754', '754', '307', '307', '269', '298', '001', '615', '885', '318', '226', '753', '430', '238', '662', '006', '318', '001', '176', '325', '290', '754', '269', '769', '899', '573', '861', '759', '001', '001', '001', '001', '001', '006', '689', '592', '759', '238', '001', '175', '290', '001', '001', '001', '001', '001', '001', '006', '001', '438', '286', '430', '269', '743', '862', '797', '001', '396', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '820', '001', '001', '001', '430', '053', '001', '001', '001', '001', '001', '001', '001', '053', '001', '823', '001', '001', '001', '001', '001', '001', '430', '001', '053', '001', '573', '001', '001', '245', '288', '001', '001', '001', '001', '001', '001', '468', '178', '555', '137', '558', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '013', '555', '001', '001', '215', '001', '001', '001', '798', '189', '001', '001', '001', '001', '245', '001', '001', '001', '001', '238', '001', '001', '001', '001', '001', '078', '001', '001', '670', '001', '001', '178', '855', '053', '189', '001', '001', '001', '001', '455', '573', '001', '001', '001', '001', '892', '001', '001', '001', '001', '001', '248', '890', '001', '001', '001', '001', '001', '001', '001', '450', '450', '450', '356', '001', '275', '001', '001', '001', '233', '001', '532', '001', '001', '001', '001', '895', '834', '001', '001', '111', '520', '895', '001', '455', '001', '001', '001', '001', '001', '001', '001', '001', '001', '318', '248', '520', '001', '001', '355', '147', '147', '147', '147', '147', '243', '001', '573', '001', '001', '001', '001', '001', '001', '001', '001', '001', '111', '892', '001', '473', '400', '834', '823', '113', '001', '001', '001', '001', '001', '001', '001', '001', '001', '698', '895', '100', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '698', '698', '824', '001', '256', '001', '001', '001', '001', '001', '001', '001', '001', '001', '147', '520', '520', '895', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '126', '248', '111', '497', '001', '548', '807', '520', '036', '400', '109', '001', '835', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '834', '356', '001', '001', '001', '243', '020', '001', '001', '001', '001', '001', '001', '001', '001', '001', '109', '823', '111', '111', '001', '001', '573', '548', '807', '001', '001', '001', '001', '001', '001', '001', '001', '520', '520', '520', '147', '377', '001', '001', '212', '001', '001', '001', '001', '147', '001', '001', '001', '001', '001', '109', '001', '001', '256', '246', '248', '824', '520', '100', '895', '455', '001', '001', '001', '001', '579', '001', '001', '001', '001', '001', '088', '790', '001', '861', '649', '576', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '134', '361', '690', '604', '690', '001', '001', '001', '001', '001', '001', '001', '001', '001', '284', '376', '045', '809', '250', '031', '001', '001', '001', '001', '154', '001', '001', '001', '001', '150', '001', '679', '001', '675', '660', '001', '001', '417', '736', '001', '006', '001', '001', '001', '001', '001', '001', '001', '001', '266', '315', '756', '467', '736', '088', '045', '172', '234', '861', '756', '761', '088', '756', '861', '789', '045', '615', '240', '091', '045', '001', '001', '001', '001', '858', '660', '761', '088', '212', '001', '001', '001', '001', '789', '736', '031', '001', '361', '001', '001', '001', '001', '001', '001', '001', '313', '837', '837', '282', '615', '360', '101', '837', '001', '129', '789', '361', '887', '895', '266', '667', '756', '154', '162', '466', '001', '756', '088', '756', '376', '001', '307', '464', '081', '081', '001', '001', '810', '001', '874', '081', '307', '001', '001', '001', '307', '689', '498', '001', '001', '001', '081', '081', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '276', '081', '001', '001', '498', '444', '003', '001', '001', '081', '001', '498', '313', '874', '895', '874', '498', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '498', '660', '810', '081', '081', '385', '001', '001', '001', '001', '001', '518', '861', '001', '001', '518', '001', '679', '001', '001', '855', '313', '001', '001', '001', '444', '013', '001', '001', '130', '001', '001', '001', '001', '001', '380', '662', '572', '001', '001', '001', '001', '013', '001', '318', '594', '001', '001', '001', '268', '001', '001', '001', '653', '662', '380', '380', '130', '001', '001', '001', '170', '001', '001', '088', '001', '013', '777', '777', '594', '001', '045', '400', '400', '682', '001', '122', '777', '001', '190', '671', '001', '001', '001', '001', '001', '013', '174', '190', '001', '318', '682', '045', '001', '001', '001', '001', '174', '001', '001', '001', '170', '170', '483', '268', '122', '001', '001', '001', '001', '001', '486', '001', '042', '001', '130', '400', '440', '075', '170', '001', '001', '148', '449', '001', '001', '050', '001', '388', '653', '001', '470', '190', '001', '001', '001', '001', '682', '001', '585', '572', '548', '594', '190', '001', '001', '001', '001', '001', '001', '001', '001', '001', '662', '111', '440', '001', '001', '001', '001', '001', '815', '175', '290', '298', '551', '551', '006', '001', '001', '001', '313', '313', '006', '001', '001', '001', '875', '875', '001', '001', '001', '307', '001', '878', '815', '307', '307', '815', '486', '867', '297', '815', '568', '001', '753', '396', '319', '001', '001', '001', '551', '176', '290', '001', '001', '438', '307', '200', '486', '001', '001', '573', '592', '006', '759', '568', '322', '176', '740', '290', '551', '006', '001', '001', '001', '001', '006', '001', '001', '001', '875', '175', '001', '548', '001', '573', '491', '875', '845', '615', '001', '214', '394', '759', '001', '615', '001', '001', '573', '860', '815', '317', '053', '810', '660', '668', '753', '319', '307', '551', '001', '313', '573', '568', '001', '238', '325', '330', '078', '753', '743', '480', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '215', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '717', '001', '001', '001', '244', '279', '288', '820', '001', '001', '001', '638', '001', '001', '430', '555', '001', '001', '001', '001', '001', '001', '001', '001', '621', '555', '001', '001', '001', '078', '296', '001', '001', '001', '001', '001', '001', '001', '001', '001', '430', '001', '189', '189', '001', '001', '001', '001', '001', '001', '001', '235', '001', '001', '001', '137', '001', '001', '001', '001', '430', '001', '001', '001', '001', '758', '001', '001', '001', '001', '001', '001', '001', '372', '558', '001', '657', '001', '001', '433', '685', '001', '215', '455', '573', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '450', '356', '001', '001', '001', '001', '233', '001', '532', '895', '834', '109', '001', '001', '001', '036', '001', '001', '001', '001', '001', '001', '001', '001', '126', '001', '563', '260', '378', '392', '392', '001', '895', '622', '001', '001', '001', '001', '001', '109', '573', '100', '075', '890', '001', '835', '573', '532', '001', '109', '109', '834', '736', '001', '001', '001', '001', '318', '001', '378', '109', '001', '001', '020', '275', '400', '001', '001', '001', '001', '001', '001', '147', '147', '895', '403', '001', '001', '001', '001', '001', '001', '001', '001', '520', '892', '400', '001', '001', '001', '001', '001', '001', '895', '109', '109', '111', '520', '001', '698', '743', '001', '001', '001', '001', '001', '001', '786', '001', '001', '835', '835', '835', '001', '001', '001', '001', '001', '001', '248', '109', '109', '743', '473', '473', '520', '520', '520', '246', '020', '113', '364', '001', '001', '001', '001', '001', '001', '001', '111', '248', '147', '532', '001', '573', '001', '001', '001', '520', '403', '364', '001', '001', '109', '109', '109', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '834', '834', '100', '109', '001', '698', '807', '109', '109', '248', '126', '130', '377', '869', '520', '001', '001', '001', '001', '001', '001', '001', '001', '520', '520', '834', '403', '122', '520', '736', '736', '622', '364', '698', '001', '045', '792', '615', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '088', '615', '615', '360', '001', '088', '001', '001', '001', '079', '154', '001', '154', '686', '282', '142', '440', '001', '001', '001', '001', '001', '001', '660', '890', '667', '360', '001', '697', '001', '266', '172', '001', '001', '570', '466', '495', '861', '790', '308', '284', '697', '790', '579', '088', '001', '001', '001', '001', '001', '001', '001', '756', '664', '679', '034', '034', '088', '088', '172', '045', '380', '001', '361', '001', '212', '001', '417', '001', '001', '001', '001', '001', '001', '001', '001', '162', '555', '001', '001', '001', '001', '001', '001', '790', '790', '001', '068', '044', '579', '440', '809', '667', '045', '162', '604', '031', '154', '162', '001', '001', '001', '001', '001', '001', '604', '380', '847', '570', '417', '154', '001', '001', '001', '001', '890', '154', '861', '001', '541', '756', '837', '040', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '887', '837', '129', '001', '361', '361', '789', '736', '154', '360', '615', '129', '792', '440', '541', '001', '001', '855', '001', '001', '001', '001', '001', '001', '081', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '172', '001', '001', '794', '547', '498', '874', '874', '001', '001', '001', '755', '001', '001', '001', '001', '001', '001', '810', '001', '368', '276', '307', '770', '001', '001', '001', '001', '001', '001', '001', '736', '736', '001', '001', '307', '755', '081', '001', '001', '001', '001', '001', '001', '810', '874', '001', '001', '001', '001', '498', '689', '689', '874', '167', '001', '001', '001', '001', '001', '001', '276', '655', '003', '498', '810', '001', '001', '081', '001', '001', '518', '001', '081', '755', '001', '001', '001', '433', '272', '524', '001', '001', '682', '170', '383', '122', '122', '001', '001', '001', '170', '001', '001', '268', '001', '433', '653', '380', '380', '001', '001', '594', '130', '001', '001', '001', '170', '001', '352', '001', '001', '088', '653', '001', '001', '001', '001', '440', '001', '001', '283', '408', '408', '449', '001', '653', '470', '130', '001', '001', '383', '001', '001', '001', '349', '268', '653', '861', '870', '001', '001', '541', '001', '001', '130', '001', '001', '001', '682', '001', '001', '671', '001', '001', '001', '541', '616', '042', '130', '594', '594', '548', '001', '170', '319', '347', '873', '001', '001', '001', '001', '001', '001', '877', '045', '001', '001', '001', '170', '682', '001', '504', '001', '042', '873', '616', '130', '302', '440', '001', '001', '001', '001', '170', '001', '001', '349', '275', '352', '001', '001', '001', '486', '524', '662', '001', '682', '682', '400', '594', '001', '236', '275', '349', '013', '662', '001', '045', '411', '268', '671', '001', '001', '001', '380', '513', '653', '174', '867', '001', '470', '411', '275', '585', '563', '010', '250', '001', '001', '001', '001', '001', '001', '001', '433', '001', '001', '001', '001', '189', '001', '758', '001', '001', '430', '245', '001', '001', '001', '001', '001', '650', '001', '001', '758', '001', '001', '001', '001', '001', '001', '001', '001', '001', '318', '001', '001', '001', '001', '001', '001', '279', '675', '001', '001', '001', '638', '758', '001', '001', '717', '001', '001', '001', '001', '001', '001', '001', '621', '245', '001', '001', '001', '001', '670', '001', '001', '001', '638', '638', '001', '001', '052', '001', '430', '001', '001', '600', '600', '001', '638', '001', '001', '001', '001', '708', '001', '001', '001', '001', '001', '001', '244', '787', '288', '318', '001', '707', '001', '656', '790', '172', '284', '172', '045', '266', '001', '001', '001', '001', '001', '001', '001', '001', '182', '847', '837', '579', '380', '001', '001', '001', '466', '088', '001', '001', '001', '001', '182', '162', '145', '792', '847', '604', '031', '031', '190', '055', '001', '001', '001', '001', '001', '001', '001', '466', '162', '001', '001', '001', '001', '001', '001', '001', '001', '001', '360', '615', '790', '079', '045', '837', '282', '282', '667', '313', '038', '887', '172', '234', '045', '172', '604', '736', '001', '001', '628', '006', '604', '579', '001', '266', '376', '466', '001', '001', '615', '001', '001', '045', '001', '667', '466', '001', '417', '360', '586', '467', '129', '045', '313', '001', '001', '670', '579', '579', '579', '001', '001', '001', '001', '001', '079', '129', '101', '555', '154', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '360', '001', '353', '034', '147', '088', '088', '234', '154', '120', '585', '313', '890', '579', '364', '376', '266', '190', '172', '001', '081', '276', '276', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '081', '547', '689', '755', '001', '001', '001', '001', '001', '689', '861', '001', '001', '001', '081', '432', '001', '001', '001', '001', '001', '276', '276', '615', '065', '001', '001', '001', '001', '001', '001', '001', '001', '081', '276', '190', '001', '001', '500', '861', '077', '081', '669', '001', '001', '001', '001', '001', '001', '001', '001', '736', '736', '689', '500', '500', '895', '001', '001', '001', '541', '653', '877', '001', '001', '001', '302', '170', '088', '001', '682', '349', '347', '174', '541', '212', '001', '440', '400', '682', '001', '001', '001', '349', '174', '616', '662', '401', '001', '001', '001', '594', '302', '001', '777', '088', '433', '001', '302', '470', '594', '440', '594', '001', '001', '001', '001', '001', '349', '055', '777', '001', '653', '001', '130', '400', '001', '001', '594', '001', '001', '001', '001', '001', '486', '486', '653', '001', '001', '001', '400', '001', '001', '001', '001', '088', '130', '001', '001', '001', '001', '594', '168', '001', '585', '283', '001', '001', '001', '001', '050', '653', '088', '001', '001', '400', '001', '001', '170', '001', '486', '524', '042', '001', '001', '470', '001', '001', '001', '318', '400', '001', '268', '483', '001', '001', '001', '001', '380', '001', '001', '001', '168', '088', '877', '272', '446', '682', '873', '671', '001', '001', '001', '001', '877', '877', '486', '388', '174', '174', '001', '594', '170', '170', '001', '001', '001', '001', '001', '572', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '001', '753', '753', '455', '759', '537', '759', '238', '238', '759', '322', '455', '001', '001', '001', '001', '299', '238', '299', '759', '537', '001', '238', '087', '572', '001', '001', '001', '001', '001', '001', '548', '001', '532', '001', '513', '212', '548', '212', '807', '001', '698', '001', '698', '100', '001', '698', '100', '807', '001', '548', '532', '001', '001', '698', '821', '001', '698', '698', '517', '307', 

**Diccionario municipios**

Se utilizó un diccionario para poder extraer los códigos de cada municipio y poder mapearlos posteriormente.

In [101]:
json_file_path = 'C:/Users/henry/Documents/jbook/Cacervix/datos/municipios.json'

with open(json_file_path, 'r', encoding = 'utf-8') as json_file:
    municipios_dict = json.load(json_file)

Mostrar diccionario

In [102]:
print(list(municipios_dict.items())[:10])
print('Existen ', len(municipios_dict), ' Municipios en el conjunto de datos.')

[('05001', 'MEDELLÍN'), ('05002', 'ABEJORRAL'), ('05004', 'ABRIAQUÍ'), ('05021', 'ALEJANDRÍA'), ('05030', 'AMAGÁ'), ('05031', 'AMALFI'), ('05034', 'ANDES'), ('05036', 'ANGELÓPOLIS'), ('05038', 'ANGOSTURA'), ('05040', 'ANORÍ')]
Existen  1122  Municipios en el conjunto de datos.

**Codificar nuevamente ***COD_MUNI*** agregandole los datos de ***COD_DPTO*****

Se le agrega cero al inicio de los números `5` y `8` para poder hacer el mapeo de datos adecuadamente y mostrar los números o códigos únicos de cada departamento.

In [103]:
tipo = data['COD_DPTO'].dtype
print(f'Teniendo en cuenta que la variable codigo es de tipo {tipo}, se agregará cero a los códigos que lo requieran.')
data.loc[data['COD_DPTO'] == '5', 'COD_DPTO'] = '05' # Se agrega cero antes del 5 y del 8
data.loc[data['CODPTORE'] == '5', 'CODPTORE'] = '05' 
data.loc[data['COD_DPTO'] == '8', 'COD_DPTO'] = '08'
data.loc[data['CODPTORE'] == '8', 'CODPTORE'] = '08'
# print('Valores únicos después de la transformación:')
# print(data[['COD_DPTO', 'CODMUNRE']].unique())

Teniendo en cuenta que la variable codigo es de tipo object, se agregará cero a los códigos que lo requieran.

**Transformar columna de códigos de muncipio**

Se garantiza que el código actual de los municipios cuente con 5dígitos y el de los dpeartamento con dos dígitos.

In [104]:
data['COD_MUNIC'] = data['COD_MUNIC'].astype(str).str.zfill(5)  # Asegura que tenga 5 dígitos
data['CODMUNRE'] = data['CODMUNRE'].astype(str).str.zfill(5)  # Asegura que tenga 5 dígitos
data['COD_DPTO'] = data['COD_DPTO'].astype(str).str.zfill(2)  # Asegura que tenga 2 dígitos
data['CODPTORE'] = data['CODPTORE'].astype(str).str.zfill(2)  # Asegura que tenga 2 dígitos

In [105]:
data['COD_MUNIC_CORREGIDO'] = data['COD_DPTO'] + data['COD_MUNIC'].str[-3:]
data['COD_MUNIC_RESIDENCIA_CORREGIDO'] = data['CODPTORE'] + data['CODMUNRE'].str[-3:]
print(data[['COD_DPTO', 'COD_MUNIC', 'COD_MUNIC_CORREGIDO', 'COD_MUNIC_RESIDENCIA_CORREGIDO']].head())

  COD_DPTO COD_MUNIC COD_MUNIC_CORREGIDO COD_MUNIC_RESIDENCIA_CORREGIDO
0       50     00313               50313                          50313
1       15     00001               15001                          15001
2       50     00606               50606                          50606
3       41     00001               41001                          41001
4       41     00001               41001                          41001

Crear columna

Se crea la columna para municpio mapeada corregida

In [106]:
tipo = data['COD_MUNIC_CORREGIDO'].dtype
print('El tipo de datos de COD_MUNIC_CORREGIDO es: ', tipo)
if data['COD_MUNIC_CORREGIDO'].dtype == 'int64':
    data["COD_MUNIC_CORREGIDO"] = data["COD_MUNIC_CORREGIDO"].astype(str).str.zfill(5)
    print(f'Y dado que era {tipo}, se convirtió a string')
    data['MUNICIPIO'] = data['COD_MUNIC'].map(municipios_dict)
    print(data['MUNICIPIO'].unique())
else:
    data['MUNICIPIO'] = data['COD_MUNIC_CORREGIDO'].map(municipios_dict)
    print(data['MUNICIPIO'].unique())

El tipo de datos de COD_MUNIC_CORREGIDO es:  object
['GRANADA' 'TUNJA' 'RESTREPO' 'NEIVA' 'AGRADO' 'TOCAIMA' 'CHÍA'
 'FUSAGASUGÁ' 'GARZÓN' 'PITALITO' 'EL COCUY' 'ACEVEDO' 'SOGAMOSO'
 'GUATEQUE' 'VILLAVICENCIO' 'ACACÍAS' 'RIVERA' 'SAN AGUSTÍN' 'MOCOA'
 'TAME' 'SARAVENA' 'PUERTO CARREÑO' 'TIMANÁ' 'VILLETA' 'MUZO' 'FLORENCIA'
 'VILLA DE SAN DIEGO DE UBATÉ' 'SAN FRANCISCO' 'SIBATÉ' 'HOBO' 'GUACHETÁ'
 'GIRARDOT' 'NEMOCÓN' 'VIANÍ' 'GACHETÁ' 'PUERTO ASÍS' 'GUADUAS' 'CABRERA'
 'SANTA MARÍA' 'TOCANCIPÁ' 'ÚTICA' 'SAN BERNARDO' 'UBAQUE' 'SOATÁ'
 'AGUAZUL' 'LA VEGA' 'CHOCONTÁ' 'SOACHA' 'FACATATIVÁ' 'YAGUARÁ' 'GUAMAL'
 'CUMARAL' 'SAN VICENTE DEL CAGUÁN' 'MADRID' 'DUITAMA'
 'SAN JUAN DE RIOSECO' 'SAN JOSÉ DEL GUAVIARE' 'CHIQUINQUIRÁ' 'GUAYATÁ'
 'SUBACHOQUE' 'ZIPAQUIRÁ' 'PUERTO LÓPEZ' 'VENTAQUEMADA' 'SAN MARTÍN'
 'PUERTO RICO' 'MEDINA' 'FUNZA' 'SILVANIA' 'VERGARA' 'TESALIA' 'LA PLATA'
 'BOGOTÁ, D.C.' 'BARRANQUILLA' 'CARTAGENA DE INDIAS' 'SANTA MARTA'
 'SINCELEJO' 'SANTIAGO DE TOLÚ' 'SAN ANDRÉS' 'MAICAO' 'ARACATACA'
 'TOLÚ VIEJO' 'MAGANGUÉ' 'PUERTO COLOMBIA' 'VALLEDUPAR' 'EL BANCO'
 'FUNDACIÓN' 'MOMPÓS' 'CHIRIGUANÁ' 'PLATO' 'CAMPO DE LA CRUZ' 'POLONUEVO'
 'AGUSTÍN CODAZZI' 'COROZAL' 'TENERIFE' 'CIÉNAGA' 'EL COPEY' 'BARANOA'
 'SAN PABLO' 'URUMITA' 'CALI' 'MIRANDA' 'PUERTO TEJADA' 'YUMBO'
 'EL CERRITO' 'YOTOCO' 'MERCADERES' 'IPIALES' 'PASTO' 'FLORIDA' 'DAGUA'
 'PATÍA' 'ZARZAL' 'TULUÁ' 'GUADALAJARA DE BUGA' 'PALMIRA' 'POPAYÁN'
 'GUACARÍ' 'INZÁ' 'CARTAGO' 'EL ÁGUILA' 'MORALES' 'LA UNIÓN' 'TORO'
 'BUGALAGRANDE' 'SANTANDER DE QUILICHAO' 'BOLÍVAR' 'TOTORÓ' 'EL ROSARIO'
 'CALIMA' 'OBANDO' 'PIENDAMÓ' 'TIMBÍO' 'ANDALUCÍA' 'BUENAVENTURA'
 'SAN ANDRÉS DE TUMACO' 'ALCALÁ' 'LA CUMBRE' 'CORINTO' 'EL TAMBO'
 'EL CAIRO' 'MEDELLÍN' 'PUERTO BERRÍO' 'BELLO' 'TARAZÁ' 'VENECIA'
 'SAN CARLOS' 'PUEBLORRICO' 'CAMPAMENTO' 'ITUANGO' 'SANTO DOMINGO'
 'REMEDIOS' 'FRONTINO' 'LA CEJA' 'APARTADÓ' 'TITIRIBÍ' 'EL BAGRE' 'AMALFI'
 'MONTERÍA' 'CAUCASIA' 'CAROLINA' 'SANTA BÁRBARA'
 'SAN BERNARDO DEL VIENTO' 'SAN JOSÉ DEL PALMAR' 'LORICA' 'SEGOVIA'
 'ACANDÍ' 'ENVIGADO' 'GUADALUPE' 'SONSÓN' 'MONTEBELLO' 'CHIGORODÓ'
 'DABEIBA' 'SOPETRÁN' 'TÁMESIS' 'RIONEGRO' 'EBÉJICO' 'BETANIA' 'VEGACHÍ'
 'SAN LUIS' 'COPACABANA' 'QUIBDÓ' 'ISTMINA' 'TURBO' 'FREDONIA' 'ITAGÜÍ'
 'CIUDAD BOLÍVAR' 'CALDAS' 'YARUMAL' 'ZARAGOZA' 'SAN RAFAEL' 'CERETÉ'
 'MONTELÍBANO' 'BUCARAMANGA' 'GIRÓN' 'MOGOTES' 'BARRANCABERMEJA' 'CÚCUTA'
 'TIBÚ' 'VILLA DEL ROSARIO' 'SAN VICENTE DE CHUCURÍ' 'OCAÑA'
 'FLORIDABLANCA' 'MATANZA' 'ÁBREGO' 'GRAMALOTE' 'ZAPATOCA' 'SALAZAR'
 'LANDÁZURI' 'PAMPLONA' 'VÉLEZ' 'SAN GIL' 'VALLE DE SAN JOSÉ'
 'MARQUETALIA' 'AGUADAS' 'ARMENIA' 'CALARCÁ' 'PEREIRA' 'IBAGUÉ'
 'MANIZALES' 'LA DORADA' 'SAMANÁ' 'PUERTO BOYACÁ' 'GUÁTICA' 'QUINCHÍA'
 'ESPINAL' 'SALAMINA' 'DOSQUEBRADAS' 'BELÉN DE UMBRÍA' 'SUPÍA' 'QUIMBAYA'
 'APÍA' 'LA VIRGINIA' 'SANTA ROSA DE CABAL' 'CAICEDONIA' 'CIRCASIA'
 'SALDAÑA' 'CHINCHINÁ' 'NATAGAIMA' 'NEIRA' 'ANSERMA' 'MARSELLA' 'BALBOA'
 'CARMEN DE APICALÁ' 'MELGAR' 'ARANZAZU' 'LA MERCED' 'MONTENEGRO'
 'PURIFICACIÓN' 'PIJAO' 'BUENAVISTA' 'VIOTÁ' 'COGUA' 'LETICIA' 'PITAL'
 'NOBSA' 'UNE' 'COTA' 'LA PALMA' 'VALPARAÍSO' 'ARBELÁEZ' 'TIPACOQUE'
 'SALADOBLANCO' 'MESETAS' 'BARAYA' 'SAN PEDRO' 'EL CARMEN DE BOLÍVAR'
 'FONSECA' 'SABANALARGA' 'LA PAZ' 'GALAPA' 'GALERAS' 'RIOHACHA' 'SOLEDAD'
 'JUAN DE ACOSTA' 'SAN JUAN NEPOMUCENO' 'MALAMBO' 'SANTO TOMÁS' 'PRADERA'
 'LA CRUZ' 'LA SIERRA' 'ROLDANILLO' 'SEVILLA' 'GUAPÍ' 'LA VICTORIA'
 'SILVIA' 'TAMINANGO' 'JAMUNDÍ' 'CANDELARIA' 'VIJES' 'TARSO' 'BARBOSA'
 'SANTA ROSA DE OSOS' 'CARACOLÍ' 'MARINILLA' 'SAHAGÚN' 'YOLOMBÓ'
 'EL SANTUARIO' 'PUEBLO NUEVO' 'NECHÍ' 'GIRARDOTA'
 'SAN PEDRO DE LOS MILAGROS' 'ANDES' 'LA ESTRELLA' 'PLANETA RICA' 'AYAPEL'
 'ANZÁ' 'URRAO' 'PEÑOL' 'ANORÍ' 'CHINÁCOTA' 'PIEDECUESTA' 'SOCORRO'
 'JESÚS MARÍA' 'SUAITA' 'CHARALÁ' 'SABANA DE TORRES' 'MANZANARES'
 'FILADELFIA' 'PALESTINA' 'LA CELIA' 'ICONONZO' 'BELALCÁZAR' 'FRESNO'
 'LÉRIDA' 'HONDA' 'VENADILLO' 'VILLAHERMOSA' 'PENSILVANIA' 'RISARALDA'
 'GUAMO' 'HERVEO' 'VILLARRICA' 'VITERBO' 'ORTEGA' 'VILLAMARÍA' 'GÉNOVA'
 'FLANDES' 'DOLORES' 'LÍBANO' 'PÁCORA' 'VICTORIA' 'PRADO' 'PAZ DE ARIPORO'
 'INÍRIDA' 'SAN JUAN DEL CESAR' 'SAMPUÉS' 'ARJONA' 'RÍO VIEJO'
 'SAN MARCOS' 'TAMALAMEQUE' 'SANTA ANA' 'SAN JERÓNIMO' 'CHINÚ' 'CARAMANTA'
 'CISNEROS' 'ARGELIA' 'ANGOSTURA' 'PURÍSIMA DE LA CONCEPCIÓN' 'SAN ROQUE'
 'HISPANIA' 'CAREPA' 'CÁCERES' 'PUERTO NARE' 'JARDÍN' 'MÁLAGA' 'ARAUQUITA'
 'CIMITARRA' 'OIBA' 'CÓRDOBA' 'LA TEBAIDA' 'ARMERO GUAYABAL' 'CHAPARRAL'
 'MARULANDA' 'PUEBLO RICO' 'MIRAFLORES' 'PAZ DE RÍO' 'GARAGOA' 'BELÉN'
 'PADILLA' 'TORIBÍO' 'PÁEZ' 'EL COLEGIO' 'APULO' 'GACHALÁ' 'SASAIMA'
 'PACHO' 'SUSA' 'CAJICÁ' 'LA MESA' 'VILLAPINZÓN' 'CAMPOALEGRE' 'GIGANTE'
 'ALGECIRAS' 'VISTAHERMOSA' 'SANTACRUZ' 'SANDONÁ' 'LOS PATIOS' 'BOCHALEMA'
 'ALMAGUER' 'SESQUILÉ' 'MITÚ' 'CAPARRAPÍ' 'NARIÑO' 'JUNÍN' 'ANOLAIMA'
 'GUASCA' 'LA PEÑA' 'FÓMEQUE' 'GUTIÉRREZ' 'SOMONDOCO' 'CÁQUEZA' 'NOCAIMA'
 'AGUA DE DIOS' 'PUERTO LLERAS' 'ISNOS' 'CURILLO' 'SIACHOQUE'
 'PUERTO SALGAR' 'SOCOTÁ' 'OVEJAS' 'SAN JACINTO' 'SIMITÍ' 'ARIGUANÍ'
 'TALAIGUA NUEVO' 'TRUJILLO' 'ROSAS' 'COCORNÁ' 'CHIMÁ' 'ALEJANDRÍA'
 'TIERRALTA' 'SANTA FÉ DE ANTIOQUIA' 'SAN VICENTE FERRER' 'MACEO' 'YONDÓ'
 'GUARNE' 'ANGELÓPOLIS' 'JERICÓ' 'SAN JOSÉ DE LA MONTAÑA'
 'EL CARMEN DE VIBORAL' 'BETULIA' 'SAN PEDRO DE URABÁ' 'HELICONIA'
 'SALGAR' 'EL ZULIA' 'CURITÍ' 'PUENTE NACIONAL' 'CONVENCIÓN' 'ARAUCA'
 'MARMATO' 'AMBALEMA' 'CAJAMARCA' 'SATIVANORTE' 'ZIPACÓN' 'MOSQUERA'
 'PUERTO GAITÁN' 'LEJANÍAS' 'TUTA' 'PAIPA' 'SANTA ROSA DE VITERBO' 'AIPE'
 'YOPAL' 'UBALÁ' 'EL DONCELLO' 'GUATAVITA' 'VILLANUEVA' 'CHIMICHAGUA'
 'BECERRIL' 'LA GLORIA' 'SAN ALBERTO' 'SABANAGRANDE' 'COLOSO'
 'SAN JUAN DE BETULIA' 'SAN ONOFRE' 'GINEBRA' 'ANSERMANUEVO' 'CAJIBÍO'
 'SOTARA' 'ARBOLETES' 'CONCORDIA' 'YALÍ' 'MUTATÁ' 'EL CARMEN DE ATRATO'
 'GIRALDO' 'CIÉNAGA DE ORO' 'SIMACOTA' 'CÁCHIRA' 'RIOBLANCO' 'RIOSUCIO'
 'FILANDIA' 'SANTUARIO' 'MISTRATÓ' 'SAN SEBASTIÁN DE MARIQUITA'
 'CASABIANCA' 'EL PAUJÍL' 'SAMACÁ' 'SUAZA' 'MANATÍ' 'SAN LUIS DE SINCÉ'
 'PROVIDENCIA' 'PIVIJAY' 'TURBACO' 'ULLOA' 'CAÑASGORDAS' 'CONDOTO' 'TADÓ'
 'SAN ANDRÉS DE CUERQUÍA' 'UNGUÍA' 'SABANETA' 'VALENCIA' 'EL PLAYÓN'
 'LEBRIJA' 'ROVIRA' 'CONCEPCIÓN' 'TOLEDO' 'VALDIVIA' 'AMAGÁ' 'SANTA ROSA'
 'MAHATES' 'MACANAL' 'CHITA' 'CARTAGENA DEL CHAIRÁ' 'MORELIA' 'PURACÉ'
 'LA JAGUA DE IBIRICO' 'PELAYA' 'CHIPAQUE' 'SOPÓ' 'PAICOL' 'REMOLINO'
 'CABUYARO' 'FLORIÁN' 'BARICHARA' 'SAN BENITO ABAD' 'LA PRIMAVERA'
 'CURUMANÍ' 'LOS ANDES' 'GÓMEZ PLATA' 'TÚQUERRES' 'SAN ESTANISLAO'
 'PUERTO WILCHES' 'CALAMAR' 'ABEJORRAL' 'MANTA' 'EL DOVIO' 'MAJAGUAL'
 'CAPITANEJO' 'GUATAPÉ' 'LIBORINA' 'SUESCA' 'PALERMO' 'COLOMBIA'
 'PUERTO LEGUÍZAMO' 'TANGUA' 'SAN LUIS DE CUBARRAL' 'CALDONO' 'IMUÉS'
 'RETIRO' 'EL PASO' 'BURITICÁ' 'SANTANA' 'PUERTO RONDÓN' 'OLAYA HERRERA'
 'SARDINATA' 'BRICEÑO' 'GAMARRA' 'SIBUNDOY' 'ATACO' 'PUERTO TRIUNFO'
 'PUERTO CONCORDIA' 'GÜICÁN' 'CONTRATACIÓN' 'CALOTO' 'URIBIA' 'OCAMONTE'
 'SABOYÁ' 'CHIMA' 'LOS SANTOS' 'YACUANQUER' 'PASCA' 'SAN PELAYO' 'MORROA'
 'TAUSA' 'AGUACHICA' 'GUATAQUÍ' 'YACOPÍ' 'MONIQUIRÁ' 'ACHÍ' 'COELLO'
 'BARRANCAS' 'DONMATÍAS' 'PALMAR DE VARELA' 'HATO' 'VERSALLES' 'SUCRE'
 'SUTATENZA' 'SAN ANTONIO DEL TEQUENDAMA' 'ALMEIDA' 'RICAURTE' 'EL GUAMO'
 'SAN JUANITO' 'REPELÓN' 'PANDI' 'MACHETÁ' 'VIGÍA DEL FUERTE' 'USIACURÍ'
 'GÜEPSA' 'CUNDAY' 'SAN ANTERO' 'SIMIJACA' 'SUAN' 'SAMANIEGO'
 'RONCESVALLES' 'PARATEBUENO' 'LOS PALMITOS' 'CUASPÚD' 'CAICEDO'
 'PINCHOTE' 'TABIO' 'ALBÁN' 'TENJO' 'LA ARGENTINA' 'CHAGUANÍ' 'CACHIPAY'
 'LA CALERA' 'TERUEL' 'SANTA LUCÍA' 'BOSCONIA' 'SOPLAVIENTO' 'RIOFRÍO'
 'BUENOS AIRES' 'VILLAGARZÓN' 'SAN ANDRÉS DE SOTAVENTO' 'BAJO BAUDÓ'
 'PUERTO LIBERTADOR' 'DURANIA' 'CHITAGÁ' 'VALLE DE SAN JUAN' 'ALVARADO'
 'COYAIMA' 'PIEDRAS' 'BUESACO' 'PEQUE' 'MOÑITOS' 'PLANADAS' 'TARQUI'
 'TURMEQUÉ' 'MANÍ' 'LA FLORIDA' 'BOJAYÁ' 'FUNES' 'NUQUÍ' 'FORTUL'
 'LURUACO' 'PONEDERA' 'CUMBAL' 'DISTRACCIÓN' 'SAN ANTONIO'
 'PUERTO CAICEDO' 'NECOCLÍ' 'SAN JUAN DE URABÁ' 'URAMITA' 'BOAVITA'
 'SANTA ROSA DEL SUR' 'ZAMBRANO' 'BERBEO' 'CERINZA' 'CHITARAQUE' 'PESCA'
 'TUNUNGUÁ' 'COTORRA' 'NIMAIMA' 'SIPÍ' 'EL RETÉN' 'BARBACOAS' 'COLÓN'
 'EL CHARCO' 'ILES' 'LINARES' 'EL CARMEN' 'PUERTO SANTANDER' 'SAN CALIXTO'
 'SALENTO' 'CERRITO' 'COROMORO' 'FALAN' 'PALOCABILDO' 'SUÁREZ' 'MONTERREY'
 'OSPINA' 'TENA' 'BARRANCO DE LOBA' 'BETÉITIVA' 'CIÉNEGA' 'CHIVOR'
 'LA UVITA' 'PAUNA' 'SAN MATEO' 'BELÉN DE LOS ANDAQUÍES' 'SAN SEBASTIÁN'
 'EL ROSAL' 'LLORÓ' 'ÍQUIRA' 'EL CALVARIO' 'ANCUYÁ' 'CONSACÁ'
 'GUAITARILLA' 'LEIVA' 'POLICARPA' 'PUPIALES' 'SAN PEDRO DE CARTAGO'
 'CARCASÍ' 'ENCISO' 'GÁMBITA' 'PALMITO' 'TÁMARA' 'TAURAMENA' 'ORITO'
 'PUERTO GUZMÁN' 'SAN DIEGO' 'SAN SEBASTIÁN DE BUENAVISTA' 'PORE' 'TOTA'
 'SUSACÓN' 'GÁMEZA' 'IZA' 'NUEVO COLÓN' 'BARRANCA DE UPÍA' 'CÓMBITA'
 'SAN LUIS DE PALENQUE' 'SAN JOSÉ DEL FRAGUA' 'FUENTE DE ORO' 'TIBASOSA'
 'ELÍAS' 'SAN MIGUEL DE SEMA' 'QUIPILE' 'PÁRAMO' 'GUACA' 'PUERTO PARRA'
 'POTOSÍ' 'CONTADERO' 'GUALMATÁN' 'VILLA RICA' 'ARBOLEDA' 'EL PEÑOL'
 'SAN LORENZO' 'LA PINTADA' 'ABRIAQUÍ' 'NORCASIA' 'ALPUJARRA'
 'CERRO DE SAN ANTONIO' 'PUERRES' 'ANZOÁTEGUI' 'SANTA ISABEL' 'NILO'
 'SORACÁ' 'SAN JUAN DE ARAMA' 'PUEBLOVIEJO' 'CÁCOTA' 'CASTILLA LA NUEVA'
 'TENZA' 'EL PIÑÓN' 'MEDIO SAN JUAN' 'ZONA BANANERA' 'OTANCHE'
 'VILLA DE LEYVA' 'SOLITA' 'MILÁN' 'SOCHA' 'NÓVITA' 'RÍO DE ORO'
 'ALGARROBO' 'ARBOLEDAS' 'ANAPOIMA' 'TIBANÁ' 'VILLAVIEJA' 'ALBANIA'
 'CICUCO' 'TUBARÁ' 'MARÍA LA BAJA' 'TASCO' 'LA MACARENA' 'AQUITANIA'
 'EL PEÑÓN' 'SUPATÁ' 'TELLO' 'EL CASTILLO' 'ALDANA' 'GUACHUCAL'
 'UNIÓN PANAMERICANA' 'ENTRERRÍOS' 'LA APARTADA' 'BUCARASICA'
 'EL CARMEN DE CHUCURÍ' 'SILOS' 'SAN MIGUEL' 'ALTOS DEL ROSARIO' 'CHISCAS'
 'MONGUA' 'RAMIRIQUÍ' 'SÁCHICA' 'ÚMBITA' 'MOMIL' 'CARMEN DE CARUPA'
 'CHOACHÍ' 'GAMA' 'MEDIO ATRATO' 'OPORAPA' 'CHIVOLO' 'CONFINES'
 'SAN JOSÉ DE MIRANDA' 'EL ROBLE' 'MURILLO' 'TRINIDAD' 'SANTIAGO'
 'DIBULLA' 'MUTISCUA' 'PIOJÓ' 'SANTA CATALINA' 'LOS CÓRDOBAS' 'PAILITAS'
 'PAJARITO' 'SAN EDUARDO' 'SAN JOSÉ DE PARE' 'TOGÜÍ' 'SOTAQUIRÁ'
 'EL DORADO' 'ALTAMIRA' 'NÁTAGA' 'GUACAMAYAS' 'MARIPÍ' 'TIBACUY' 'OICATÁ'
 'TIMBIQUÍ' 'CHACHAGÜÍ' 'LABATECA' 'CHIPATÁ' 'TEORAMA' 'MANAURE'
 'QUEBRADANEGRA' 'CRAVO NORTE' 'CANTAGALLO' 'TIQUISIO' 'TURBANÁ' 'RONDÓN'
 'SATIVASUR' 'HATONUEVO' 'NUEVA GRANADA' 'LA PLAYA' 'MOLAGAVITA'
 'VALLE DEL GUAMUEZ' 'EL RETORNO' 'GUARANDA' 'PALMAS DEL SOCORRO'
 'LA MONTAÑITA' 'SAN ZENÓN' 'EL MOLINO' 'VIRACACHÁ' 'ZETAQUIRA' 'OLAYA'
 'JENESANO' 'CORRALES' 'COVEÑAS' 'PAIME' 'SAN PABLO DE BORBUR' 'TOPAIPÍ'
 'VETAS' 'HERRÁN' 'PAMPLONITA' 'LA ESPERANZA' 'LA LLANADA' 'EL GUACAMAYO'
 'GUACHENÉ' 'SANTA BÁRBARA DE PINTO' 'ARROYOHONDO' 'PINILLOS'
 'PUERTO ESCONDIDO' 'BAHÍA SOLANO' 'QUÍPAMA' 'CUCUTILLA' 'ARATOCA'
 'CEPITÁ' 'ASTREA' 'CAIMITO' 'CLEMENCIA' 'SAPUYES' 'PIJIÑO DEL CARMEN'
 'EL ESPINO' 'CUCUNUBÁ' 'TIBIRITA' 'TARAPACÁ' 'MURINDÓ' 'PIAMONTE'
 'SÁCAMA' 'MALLAMA' 'OROCUÉ' 'LA CAPILLA' 'CHINAVITA' 'ATRATO'
 'VILLA CARO' 'SAN CARLOS DE GUAROA' 'CHARTA' 'PUEBLO BELLO'
 'LABRANZAGRANDE' 'BOYACÁ' 'SUTAMARCHÁN' 'MANAURE BALCÓN DEL CESAR'
 'RÁQUIRA' 'SAN CRISTÓBAL' 'SAN MARTÍN DE LOBA' 'SAN FERNANDO' 'FÚQUENE'
 'SABANAS DE SAN ÁNGEL' 'EL TARRA' 'EL TABLÓN DE GÓMEZ' 'HATILLO DE LOBA'
 'NUNCHÍA' 'JAMBALÓ' 'TINJACÁ' 'GACHANCIPÁ' 'CHÍQUIZA' 'REGIDOR' 'COPER'
 'LENGUAZAQUE' 'SURATÁ' 'CHALÁN' 'TOCA' 'GALÁN' 'PACHAVITA' 'COVARACHÍA'
 'LA BELLEZA' 'FLORESTA' 'RAGONVALIA' 'ONZAGA' 'NOROSÍ' 'CANALETE'
 'GUAPOTÁ' 'HATO COROZAL' 'TUCHÍN' 'CUMARIBO' 'CARURÚ' 'SANTA ROSALÍA'
 'URIBE' 'SITIONUEVO' 'BOJACÁ' 'LA PEDRERA' nan]

Municipio de residencia

In [107]:
tipo = data['COD_MUNIC_CORREGIDO'].dtype
print('El tipo de datos de COD_MUNIC_CORREGIDO es: ', tipo)
if data['COD_MUNIC_CORREGIDO'].dtype == 'int64':
    data["COD_MUNIC_CORREGIDO"] = data["COD_MUNIC_CORREGIDO"].astype(str).str.zfill(5)
    print(f'Y dado que era {tipo}, se convirtió a string')
    data['MUNICIPIO DE RESIDENCIA'] = data['COD_MUNIC'].map(municipios_dict)
    print(data['MUNICIPIO DE RESIDENCIA'].unique())
else:
    data['MUNICIPIO DE RESIDENCIA'] = data['COD_MUNIC_CORREGIDO'].map(municipios_dict)
    print(data['MUNICIPIO DE RESIDENCIA'].unique())

El tipo de datos de COD_MUNIC_CORREGIDO es:  object
['GRANADA' 'TUNJA' 'RESTREPO' 'NEIVA' 'AGRADO' 'TOCAIMA' 'CHÍA'
 'FUSAGASUGÁ' 'GARZÓN' 'PITALITO' 'EL COCUY' 'ACEVEDO' 'SOGAMOSO'
 'GUATEQUE' 'VILLAVICENCIO' 'ACACÍAS' 'RIVERA' 'SAN AGUSTÍN' 'MOCOA'
 'TAME' 'SARAVENA' 'PUERTO CARREÑO' 'TIMANÁ' 'VILLETA' 'MUZO' 'FLORENCIA'
 'VILLA DE SAN DIEGO DE UBATÉ' 'SAN FRANCISCO' 'SIBATÉ' 'HOBO' 'GUACHETÁ'
 'GIRARDOT' 'NEMOCÓN' 'VIANÍ' 'GACHETÁ' 'PUERTO ASÍS' 'GUADUAS' 'CABRERA'
 'SANTA MARÍA' 'TOCANCIPÁ' 'ÚTICA' 'SAN BERNARDO' 'UBAQUE' 'SOATÁ'
 'AGUAZUL' 'LA VEGA' 'CHOCONTÁ' 'SOACHA' 'FACATATIVÁ' 'YAGUARÁ' 'GUAMAL'
 'CUMARAL' 'SAN VICENTE DEL CAGUÁN' 'MADRID' 'DUITAMA'
 'SAN JUAN DE RIOSECO' 'SAN JOSÉ DEL GUAVIARE' 'CHIQUINQUIRÁ' 'GUAYATÁ'
 'SUBACHOQUE' 'ZIPAQUIRÁ' 'PUERTO LÓPEZ' 'VENTAQUEMADA' 'SAN MARTÍN'
 'PUERTO RICO' 'MEDINA' 'FUNZA' 'SILVANIA' 'VERGARA' 'TESALIA' 'LA PLATA'
 'BOGOTÁ, D.C.' 'BARRANQUILLA' 'CARTAGENA DE INDIAS' 'SANTA MARTA'
 'SINCELEJO' 'SANTIAGO DE TOLÚ' 'SAN ANDRÉS' 'MAICAO' 'ARACATACA'
 'TOLÚ VIEJO' 'MAGANGUÉ' 'PUERTO COLOMBIA' 'VALLEDUPAR' 'EL BANCO'
 'FUNDACIÓN' 'MOMPÓS' 'CHIRIGUANÁ' 'PLATO' 'CAMPO DE LA CRUZ' 'POLONUEVO'
 'AGUSTÍN CODAZZI' 'COROZAL' 'TENERIFE' 'CIÉNAGA' 'EL COPEY' 'BARANOA'
 'SAN PABLO' 'URUMITA' 'CALI' 'MIRANDA' 'PUERTO TEJADA' 'YUMBO'
 'EL CERRITO' 'YOTOCO' 'MERCADERES' 'IPIALES' 'PASTO' 'FLORIDA' 'DAGUA'
 'PATÍA' 'ZARZAL' 'TULUÁ' 'GUADALAJARA DE BUGA' 'PALMIRA' 'POPAYÁN'
 'GUACARÍ' 'INZÁ' 'CARTAGO' 'EL ÁGUILA' 'MORALES' 'LA UNIÓN' 'TORO'
 'BUGALAGRANDE' 'SANTANDER DE QUILICHAO' 'BOLÍVAR' 'TOTORÓ' 'EL ROSARIO'
 'CALIMA' 'OBANDO' 'PIENDAMÓ' 'TIMBÍO' 'ANDALUCÍA' 'BUENAVENTURA'
 'SAN ANDRÉS DE TUMACO' 'ALCALÁ' 'LA CUMBRE' 'CORINTO' 'EL TAMBO'
 'EL CAIRO' 'MEDELLÍN' 'PUERTO BERRÍO' 'BELLO' 'TARAZÁ' 'VENECIA'
 'SAN CARLOS' 'PUEBLORRICO' 'CAMPAMENTO' 'ITUANGO' 'SANTO DOMINGO'
 'REMEDIOS' 'FRONTINO' 'LA CEJA' 'APARTADÓ' 'TITIRIBÍ' 'EL BAGRE' 'AMALFI'
 'MONTERÍA' 'CAUCASIA' 'CAROLINA' 'SANTA BÁRBARA'
 'SAN BERNARDO DEL VIENTO' 'SAN JOSÉ DEL PALMAR' 'LORICA' 'SEGOVIA'
 'ACANDÍ' 'ENVIGADO' 'GUADALUPE' 'SONSÓN' 'MONTEBELLO' 'CHIGORODÓ'
 'DABEIBA' 'SOPETRÁN' 'TÁMESIS' 'RIONEGRO' 'EBÉJICO' 'BETANIA' 'VEGACHÍ'
 'SAN LUIS' 'COPACABANA' 'QUIBDÓ' 'ISTMINA' 'TURBO' 'FREDONIA' 'ITAGÜÍ'
 'CIUDAD BOLÍVAR' 'CALDAS' 'YARUMAL' 'ZARAGOZA' 'SAN RAFAEL' 'CERETÉ'
 'MONTELÍBANO' 'BUCARAMANGA' 'GIRÓN' 'MOGOTES' 'BARRANCABERMEJA' 'CÚCUTA'
 'TIBÚ' 'VILLA DEL ROSARIO' 'SAN VICENTE DE CHUCURÍ' 'OCAÑA'
 'FLORIDABLANCA' 'MATANZA' 'ÁBREGO' 'GRAMALOTE' 'ZAPATOCA' 'SALAZAR'
 'LANDÁZURI' 'PAMPLONA' 'VÉLEZ' 'SAN GIL' 'VALLE DE SAN JOSÉ'
 'MARQUETALIA' 'AGUADAS' 'ARMENIA' 'CALARCÁ' 'PEREIRA' 'IBAGUÉ'
 'MANIZALES' 'LA DORADA' 'SAMANÁ' 'PUERTO BOYACÁ' 'GUÁTICA' 'QUINCHÍA'
 'ESPINAL' 'SALAMINA' 'DOSQUEBRADAS' 'BELÉN DE UMBRÍA' 'SUPÍA' 'QUIMBAYA'
 'APÍA' 'LA VIRGINIA' 'SANTA ROSA DE CABAL' 'CAICEDONIA' 'CIRCASIA'
 'SALDAÑA' 'CHINCHINÁ' 'NATAGAIMA' 'NEIRA' 'ANSERMA' 'MARSELLA' 'BALBOA'
 'CARMEN DE APICALÁ' 'MELGAR' 'ARANZAZU' 'LA MERCED' 'MONTENEGRO'
 'PURIFICACIÓN' 'PIJAO' 'BUENAVISTA' 'VIOTÁ' 'COGUA' 'LETICIA' 'PITAL'
 'NOBSA' 'UNE' 'COTA' 'LA PALMA' 'VALPARAÍSO' 'ARBELÁEZ' 'TIPACOQUE'
 'SALADOBLANCO' 'MESETAS' 'BARAYA' 'SAN PEDRO' 'EL CARMEN DE BOLÍVAR'
 'FONSECA' 'SABANALARGA' 'LA PAZ' 'GALAPA' 'GALERAS' 'RIOHACHA' 'SOLEDAD'
 'JUAN DE ACOSTA' 'SAN JUAN NEPOMUCENO' 'MALAMBO' 'SANTO TOMÁS' 'PRADERA'
 'LA CRUZ' 'LA SIERRA' 'ROLDANILLO' 'SEVILLA' 'GUAPÍ' 'LA VICTORIA'
 'SILVIA' 'TAMINANGO' 'JAMUNDÍ' 'CANDELARIA' 'VIJES' 'TARSO' 'BARBOSA'
 'SANTA ROSA DE OSOS' 'CARACOLÍ' 'MARINILLA' 'SAHAGÚN' 'YOLOMBÓ'
 'EL SANTUARIO' 'PUEBLO NUEVO' 'NECHÍ' 'GIRARDOTA'
 'SAN PEDRO DE LOS MILAGROS' 'ANDES' 'LA ESTRELLA' 'PLANETA RICA' 'AYAPEL'
 'ANZÁ' 'URRAO' 'PEÑOL' 'ANORÍ' 'CHINÁCOTA' 'PIEDECUESTA' 'SOCORRO'
 'JESÚS MARÍA' 'SUAITA' 'CHARALÁ' 'SABANA DE TORRES' 'MANZANARES'
 'FILADELFIA' 'PALESTINA' 'LA CELIA' 'ICONONZO' 'BELALCÁZAR' 'FRESNO'
 'LÉRIDA' 'HONDA' 'VENADILLO' 'VILLAHERMOSA' 'PENSILVANIA' 'RISARALDA'
 'GUAMO' 'HERVEO' 'VILLARRICA' 'VITERBO' 'ORTEGA' 'VILLAMARÍA' 'GÉNOVA'
 'FLANDES' 'DOLORES' 'LÍBANO' 'PÁCORA' 'VICTORIA' 'PRADO' 'PAZ DE ARIPORO'
 'INÍRIDA' 'SAN JUAN DEL CESAR' 'SAMPUÉS' 'ARJONA' 'RÍO VIEJO'
 'SAN MARCOS' 'TAMALAMEQUE' 'SANTA ANA' 'SAN JERÓNIMO' 'CHINÚ' 'CARAMANTA'
 'CISNEROS' 'ARGELIA' 'ANGOSTURA' 'PURÍSIMA DE LA CONCEPCIÓN' 'SAN ROQUE'
 'HISPANIA' 'CAREPA' 'CÁCERES' 'PUERTO NARE' 'JARDÍN' 'MÁLAGA' 'ARAUQUITA'
 'CIMITARRA' 'OIBA' 'CÓRDOBA' 'LA TEBAIDA' 'ARMERO GUAYABAL' 'CHAPARRAL'
 'MARULANDA' 'PUEBLO RICO' 'MIRAFLORES' 'PAZ DE RÍO' 'GARAGOA' 'BELÉN'
 'PADILLA' 'TORIBÍO' 'PÁEZ' 'EL COLEGIO' 'APULO' 'GACHALÁ' 'SASAIMA'
 'PACHO' 'SUSA' 'CAJICÁ' 'LA MESA' 'VILLAPINZÓN' 'CAMPOALEGRE' 'GIGANTE'
 'ALGECIRAS' 'VISTAHERMOSA' 'SANTACRUZ' 'SANDONÁ' 'LOS PATIOS' 'BOCHALEMA'
 'ALMAGUER' 'SESQUILÉ' 'MITÚ' 'CAPARRAPÍ' 'NARIÑO' 'JUNÍN' 'ANOLAIMA'
 'GUASCA' 'LA PEÑA' 'FÓMEQUE' 'GUTIÉRREZ' 'SOMONDOCO' 'CÁQUEZA' 'NOCAIMA'
 'AGUA DE DIOS' 'PUERTO LLERAS' 'ISNOS' 'CURILLO' 'SIACHOQUE'
 'PUERTO SALGAR' 'SOCOTÁ' 'OVEJAS' 'SAN JACINTO' 'SIMITÍ' 'ARIGUANÍ'
 'TALAIGUA NUEVO' 'TRUJILLO' 'ROSAS' 'COCORNÁ' 'CHIMÁ' 'ALEJANDRÍA'
 'TIERRALTA' 'SANTA FÉ DE ANTIOQUIA' 'SAN VICENTE FERRER' 'MACEO' 'YONDÓ'
 'GUARNE' 'ANGELÓPOLIS' 'JERICÓ' 'SAN JOSÉ DE LA MONTAÑA'
 'EL CARMEN DE VIBORAL' 'BETULIA' 'SAN PEDRO DE URABÁ' 'HELICONIA'
 'SALGAR' 'EL ZULIA' 'CURITÍ' 'PUENTE NACIONAL' 'CONVENCIÓN' 'ARAUCA'
 'MARMATO' 'AMBALEMA' 'CAJAMARCA' 'SATIVANORTE' 'ZIPACÓN' 'MOSQUERA'
 'PUERTO GAITÁN' 'LEJANÍAS' 'TUTA' 'PAIPA' 'SANTA ROSA DE VITERBO' 'AIPE'
 'YOPAL' 'UBALÁ' 'EL DONCELLO' 'GUATAVITA' 'VILLANUEVA' 'CHIMICHAGUA'
 'BECERRIL' 'LA GLORIA' 'SAN ALBERTO' 'SABANAGRANDE' 'COLOSO'
 'SAN JUAN DE BETULIA' 'SAN ONOFRE' 'GINEBRA' 'ANSERMANUEVO' 'CAJIBÍO'
 'SOTARA' 'ARBOLETES' 'CONCORDIA' 'YALÍ' 'MUTATÁ' 'EL CARMEN DE ATRATO'
 'GIRALDO' 'CIÉNAGA DE ORO' 'SIMACOTA' 'CÁCHIRA' 'RIOBLANCO' 'RIOSUCIO'
 'FILANDIA' 'SANTUARIO' 'MISTRATÓ' 'SAN SEBASTIÁN DE MARIQUITA'
 'CASABIANCA' 'EL PAUJÍL' 'SAMACÁ' 'SUAZA' 'MANATÍ' 'SAN LUIS DE SINCÉ'
 'PROVIDENCIA' 'PIVIJAY' 'TURBACO' 'ULLOA' 'CAÑASGORDAS' 'CONDOTO' 'TADÓ'
 'SAN ANDRÉS DE CUERQUÍA' 'UNGUÍA' 'SABANETA' 'VALENCIA' 'EL PLAYÓN'
 'LEBRIJA' 'ROVIRA' 'CONCEPCIÓN' 'TOLEDO' 'VALDIVIA' 'AMAGÁ' 'SANTA ROSA'
 'MAHATES' 'MACANAL' 'CHITA' 'CARTAGENA DEL CHAIRÁ' 'MORELIA' 'PURACÉ'
 'LA JAGUA DE IBIRICO' 'PELAYA' 'CHIPAQUE' 'SOPÓ' 'PAICOL' 'REMOLINO'
 'CABUYARO' 'FLORIÁN' 'BARICHARA' 'SAN BENITO ABAD' 'LA PRIMAVERA'
 'CURUMANÍ' 'LOS ANDES' 'GÓMEZ PLATA' 'TÚQUERRES' 'SAN ESTANISLAO'
 'PUERTO WILCHES' 'CALAMAR' 'ABEJORRAL' 'MANTA' 'EL DOVIO' 'MAJAGUAL'
 'CAPITANEJO' 'GUATAPÉ' 'LIBORINA' 'SUESCA' 'PALERMO' 'COLOMBIA'
 'PUERTO LEGUÍZAMO' 'TANGUA' 'SAN LUIS DE CUBARRAL' 'CALDONO' 'IMUÉS'
 'RETIRO' 'EL PASO' 'BURITICÁ' 'SANTANA' 'PUERTO RONDÓN' 'OLAYA HERRERA'
 'SARDINATA' 'BRICEÑO' 'GAMARRA' 'SIBUNDOY' 'ATACO' 'PUERTO TRIUNFO'
 'PUERTO CONCORDIA' 'GÜICÁN' 'CONTRATACIÓN' 'CALOTO' 'URIBIA' 'OCAMONTE'
 'SABOYÁ' 'CHIMA' 'LOS SANTOS' 'YACUANQUER' 'PASCA' 'SAN PELAYO' 'MORROA'
 'TAUSA' 'AGUACHICA' 'GUATAQUÍ' 'YACOPÍ' 'MONIQUIRÁ' 'ACHÍ' 'COELLO'
 'BARRANCAS' 'DONMATÍAS' 'PALMAR DE VARELA' 'HATO' 'VERSALLES' 'SUCRE'
 'SUTATENZA' 'SAN ANTONIO DEL TEQUENDAMA' 'ALMEIDA' 'RICAURTE' 'EL GUAMO'
 'SAN JUANITO' 'REPELÓN' 'PANDI' 'MACHETÁ' 'VIGÍA DEL FUERTE' 'USIACURÍ'
 'GÜEPSA' 'CUNDAY' 'SAN ANTERO' 'SIMIJACA' 'SUAN' 'SAMANIEGO'
 'RONCESVALLES' 'PARATEBUENO' 'LOS PALMITOS' 'CUASPÚD' 'CAICEDO'
 'PINCHOTE' 'TABIO' 'ALBÁN' 'TENJO' 'LA ARGENTINA' 'CHAGUANÍ' 'CACHIPAY'
 'LA CALERA' 'TERUEL' 'SANTA LUCÍA' 'BOSCONIA' 'SOPLAVIENTO' 'RIOFRÍO'
 'BUENOS AIRES' 'VILLAGARZÓN' 'SAN ANDRÉS DE SOTAVENTO' 'BAJO BAUDÓ'
 'PUERTO LIBERTADOR' 'DURANIA' 'CHITAGÁ' 'VALLE DE SAN JUAN' 'ALVARADO'
 'COYAIMA' 'PIEDRAS' 'BUESACO' 'PEQUE' 'MOÑITOS' 'PLANADAS' 'TARQUI'
 'TURMEQUÉ' 'MANÍ' 'LA FLORIDA' 'BOJAYÁ' 'FUNES' 'NUQUÍ' 'FORTUL'
 'LURUACO' 'PONEDERA' 'CUMBAL' 'DISTRACCIÓN' 'SAN ANTONIO'
 'PUERTO CAICEDO' 'NECOCLÍ' 'SAN JUAN DE URABÁ' 'URAMITA' 'BOAVITA'
 'SANTA ROSA DEL SUR' 'ZAMBRANO' 'BERBEO' 'CERINZA' 'CHITARAQUE' 'PESCA'
 'TUNUNGUÁ' 'COTORRA' 'NIMAIMA' 'SIPÍ' 'EL RETÉN' 'BARBACOAS' 'COLÓN'
 'EL CHARCO' 'ILES' 'LINARES' 'EL CARMEN' 'PUERTO SANTANDER' 'SAN CALIXTO'
 'SALENTO' 'CERRITO' 'COROMORO' 'FALAN' 'PALOCABILDO' 'SUÁREZ' 'MONTERREY'
 'OSPINA' 'TENA' 'BARRANCO DE LOBA' 'BETÉITIVA' 'CIÉNEGA' 'CHIVOR'
 'LA UVITA' 'PAUNA' 'SAN MATEO' 'BELÉN DE LOS ANDAQUÍES' 'SAN SEBASTIÁN'
 'EL ROSAL' 'LLORÓ' 'ÍQUIRA' 'EL CALVARIO' 'ANCUYÁ' 'CONSACÁ'
 'GUAITARILLA' 'LEIVA' 'POLICARPA' 'PUPIALES' 'SAN PEDRO DE CARTAGO'
 'CARCASÍ' 'ENCISO' 'GÁMBITA' 'PALMITO' 'TÁMARA' 'TAURAMENA' 'ORITO'
 'PUERTO GUZMÁN' 'SAN DIEGO' 'SAN SEBASTIÁN DE BUENAVISTA' 'PORE' 'TOTA'
 'SUSACÓN' 'GÁMEZA' 'IZA' 'NUEVO COLÓN' 'BARRANCA DE UPÍA' 'CÓMBITA'
 'SAN LUIS DE PALENQUE' 'SAN JOSÉ DEL FRAGUA' 'FUENTE DE ORO' 'TIBASOSA'
 'ELÍAS' 'SAN MIGUEL DE SEMA' 'QUIPILE' 'PÁRAMO' 'GUACA' 'PUERTO PARRA'
 'POTOSÍ' 'CONTADERO' 'GUALMATÁN' 'VILLA RICA' 'ARBOLEDA' 'EL PEÑOL'
 'SAN LORENZO' 'LA PINTADA' 'ABRIAQUÍ' 'NORCASIA' 'ALPUJARRA'
 'CERRO DE SAN ANTONIO' 'PUERRES' 'ANZOÁTEGUI' 'SANTA ISABEL' 'NILO'
 'SORACÁ' 'SAN JUAN DE ARAMA' 'PUEBLOVIEJO' 'CÁCOTA' 'CASTILLA LA NUEVA'
 'TENZA' 'EL PIÑÓN' 'MEDIO SAN JUAN' 'ZONA BANANERA' 'OTANCHE'
 'VILLA DE LEYVA' 'SOLITA' 'MILÁN' 'SOCHA' 'NÓVITA' 'RÍO DE ORO'
 'ALGARROBO' 'ARBOLEDAS' 'ANAPOIMA' 'TIBANÁ' 'VILLAVIEJA' 'ALBANIA'
 'CICUCO' 'TUBARÁ' 'MARÍA LA BAJA' 'TASCO' 'LA MACARENA' 'AQUITANIA'
 'EL PEÑÓN' 'SUPATÁ' 'TELLO' 'EL CASTILLO' 'ALDANA' 'GUACHUCAL'
 'UNIÓN PANAMERICANA' 'ENTRERRÍOS' 'LA APARTADA' 'BUCARASICA'
 'EL CARMEN DE CHUCURÍ' 'SILOS' 'SAN MIGUEL' 'ALTOS DEL ROSARIO' 'CHISCAS'
 'MONGUA' 'RAMIRIQUÍ' 'SÁCHICA' 'ÚMBITA' 'MOMIL' 'CARMEN DE CARUPA'
 'CHOACHÍ' 'GAMA' 'MEDIO ATRATO' 'OPORAPA' 'CHIVOLO' 'CONFINES'
 'SAN JOSÉ DE MIRANDA' 'EL ROBLE' 'MURILLO' 'TRINIDAD' 'SANTIAGO'
 'DIBULLA' 'MUTISCUA' 'PIOJÓ' 'SANTA CATALINA' 'LOS CÓRDOBAS' 'PAILITAS'
 'PAJARITO' 'SAN EDUARDO' 'SAN JOSÉ DE PARE' 'TOGÜÍ' 'SOTAQUIRÁ'
 'EL DORADO' 'ALTAMIRA' 'NÁTAGA' 'GUACAMAYAS' 'MARIPÍ' 'TIBACUY' 'OICATÁ'
 'TIMBIQUÍ' 'CHACHAGÜÍ' 'LABATECA' 'CHIPATÁ' 'TEORAMA' 'MANAURE'
 'QUEBRADANEGRA' 'CRAVO NORTE' 'CANTAGALLO' 'TIQUISIO' 'TURBANÁ' 'RONDÓN'
 'SATIVASUR' 'HATONUEVO' 'NUEVA GRANADA' 'LA PLAYA' 'MOLAGAVITA'
 'VALLE DEL GUAMUEZ' 'EL RETORNO' 'GUARANDA' 'PALMAS DEL SOCORRO'
 'LA MONTAÑITA' 'SAN ZENÓN' 'EL MOLINO' 'VIRACACHÁ' 'ZETAQUIRA' 'OLAYA'
 'JENESANO' 'CORRALES' 'COVEÑAS' 'PAIME' 'SAN PABLO DE BORBUR' 'TOPAIPÍ'
 'VETAS' 'HERRÁN' 'PAMPLONITA' 'LA ESPERANZA' 'LA LLANADA' 'EL GUACAMAYO'
 'GUACHENÉ' 'SANTA BÁRBARA DE PINTO' 'ARROYOHONDO' 'PINILLOS'
 'PUERTO ESCONDIDO' 'BAHÍA SOLANO' 'QUÍPAMA' 'CUCUTILLA' 'ARATOCA'
 'CEPITÁ' 'ASTREA' 'CAIMITO' 'CLEMENCIA' 'SAPUYES' 'PIJIÑO DEL CARMEN'
 'EL ESPINO' 'CUCUNUBÁ' 'TIBIRITA' 'TARAPACÁ' 'MURINDÓ' 'PIAMONTE'
 'SÁCAMA' 'MALLAMA' 'OROCUÉ' 'LA CAPILLA' 'CHINAVITA' 'ATRATO'
 'VILLA CARO' 'SAN CARLOS DE GUAROA' 'CHARTA' 'PUEBLO BELLO'
 'LABRANZAGRANDE' 'BOYACÁ' 'SUTAMARCHÁN' 'MANAURE BALCÓN DEL CESAR'
 'RÁQUIRA' 'SAN CRISTÓBAL' 'SAN MARTÍN DE LOBA' 'SAN FERNANDO' 'FÚQUENE'
 'SABANAS DE SAN ÁNGEL' 'EL TARRA' 'EL TABLÓN DE GÓMEZ' 'HATILLO DE LOBA'
 'NUNCHÍA' 'JAMBALÓ' 'TINJACÁ' 'GACHANCIPÁ' 'CHÍQUIZA' 'REGIDOR' 'COPER'
 'LENGUAZAQUE' 'SURATÁ' 'CHALÁN' 'TOCA' 'GALÁN' 'PACHAVITA' 'COVARACHÍA'
 'LA BELLEZA' 'FLORESTA' 'RAGONVALIA' 'ONZAGA' 'NOROSÍ' 'CANALETE'
 'GUAPOTÁ' 'HATO COROZAL' 'TUCHÍN' 'CUMARIBO' 'CARURÚ' 'SANTA ROSALÍA'
 'URIBE' 'SITIONUEVO' 'BOJACÁ' 'LA PEDRERA' nan]

In [19]:
data[['MUNICIPIO', 'MUNICIPIO DE RESIDENCIA']].head()

  MUNICIPIO MUNICIPIO DE RESIDENCIA
0   GRANADA                 GRANADA
1     TUNJA                   TUNJA
2  RESTREPO                RESTREPO
3     NEIVA                   NEIVA
4     NEIVA                   NEIVA

In [108]:
# Mapear municipios
data["MUNICIPIO"] = data["COD_MUNIC_CORREGIDO"].map(municipios_dict)
data["MUNICIPIO DE RESIDENCIA"] = data["COD_MUNIC_RESIDENCIA_CORREGIDO"].map(municipios_dict)

# Verificar si hay valores NaN
nan_count1 = data["MUNICIPIO"].isna().sum()
nan_count2 = data['MUNICIPIO DE RESIDENCIA'].isna().sum()
print(f"Cantidad de valores NaN en MUNICIPIO DE RESIDENCIA: {nan_count2}")
print(f"Cantidad de valores NaN en MUNICIPIO: {nan_count1}")

Cantidad de valores NaN en MUNICIPIO DE RESIDENCIA: 6154
Cantidad de valores NaN en MUNICIPIO: 5671

Reorganizar la columna

In [109]:
del data['COD_MUNIC'] # Eliminamos la columna
del data['COD_MUNIC_CORREGIDO']
del data['COD_DPTO']

In [110]:
columnas = ['DEPARTAMENTO', 'DEPARTAMENTO DE RESIDENCIA',  'MUNICIPIO', 'MUNICIPIO DE RESIDENCIA'] + [col for col in data.columns if col not in ['DEPARTAMENTO', 'DEPARTAMENTO DE RESIDENCIA', 'MUNICIPIO', 'MUNICIPIO DE RESIDENCIA']]
data16 = data[columnas]
display(HTML(data16.head(10).to_html()))

Observar el área de defunción y tipo de defunción

In [165]:
print("Áreas de defunción únicas: ", data['A_DEFUN'].unique())
print("Sitios de defunción únicos: ", data['SIT_DEFUN'].unique())

Áreas de defunción únicas:  ['1' '2' '3']
Sitios de defunción únicos:  ['2' '1' '4' '3' '6' '5' '9']

Diccionario para codifocar area y sitio

In [111]:
area_dict = {
    '1': 'URBANA',
    '2': 'RURAL',
    '3': 'SIN INFORMACIÓN'
}

sitio_dict = {
    '1': 'HOSPITAL O CLÍNICA',
    '2': 'CASA',
    '3': 'OTRO SITIO',
    '4': 'SIN INFORMACIÓN'
}

In [124]:
# Asegurar que las columnas sean str
data['A_DEFUN'] = data['A_DEFUN'].astype(str)
data['SIT_DEFUN'] = data['SIT_DEFUN'].astype(str)

# Mapear correctamente
data['AREA_DEFUN'] = data['A_DEFUN'].map(area_dict)
data['SITIO_DEFUN'] = data['SIT_DEFUN'].map(sitio_dict)

Organizar las columnas

In [125]:
# Organizar las variables al final
columnas = ['A_DEFUN', 'AREA_DEFUN', 'SIT_DEFUN', 'SITIO_DEFUN']
columnas_quedan = [col for col in data.columns if col not in columnas]
data = data[columnas_quedan + columnas]

Análiis de datos únicos por categoría

In [114]:
categorical_columns = ['SEXO', 'NIVEL_EDU', 'EST_CIVIL', 'SIMUERTEPO', 'OCUPACION']

unique_count = data[categorical_columns].nunique()
unique_values ={col: data[col].unique() for col in categorical_columns}

for col in categorical_columns:
    print(f"Variable: {col}")
    print(f"Número de categorías únicas: {unique_count[col]}")
    print(f"Categorías únicas: {unique_values[col]}")

Variable: SEXO
Número de categorías únicas: 1
Categorías únicas: ['2']
Variable: NIVEL_EDU
Número de categorías únicas: 15
Categorías únicas: ['' '2' '5' '6' '3' '4' '1' '9' '8' '7' '99' '13' '10' '11' '12']
Variable: EST_CIVIL
Número de categorías únicas: 7
Categorías únicas: ['1' '2' '3' '5' '4' '9' '6']
Variable: SIMUERTEPO
Número de categorías únicas: 5
Categorías únicas: ['' '9' '1' '2' '"']
Variable: OCUPACION
Número de categorías únicas: 549
Categorías únicas: ['' 'AMA DE CASA' 'AGRICULTOR' 'HOGAR' 'FINCA' 'OFICIOS VARIOS'
 'COMERCIANTE DE FLORES' 'SECRETARIA' 'NINGUNO' 'CESANTE' 'VENDEDORA'
 'TRABAJADOR INDEPENDIENTE' 'SIN OCUPACION' 'SIN INFORMACION'
 'OFICIOS DOMESTICOS' 'NINGUNA' 'AMA DECASA' 'DISCAPACITADA'
 'EMPLEADA DOMESTICA' 'AGRICULTURA' '0' 'GERENTE FINANCIERO'
 'AMA DE  CASA' 'NUTRICIONISTA' 'SERVICIOS GENERALES'
 'SUPERIORA PROVINCIAL' 'HIOGAR' 'OPERARIA' 'TRABAJADORA DEL CAMPO'
 'OPERARIA MAQUINA PLANA' 'PROFESORES DE EDUCACIËN PRIMARIA' 'EMPLEADA'
 'MODISTA' 'PENSIONADO' 'VENDEDORES, DEMOSTRADORES DE TIENDAS Y ALMACENES'
 'EMPLEADA DE SERVICIO' 'OFIVIOS VARIOS' 'AUXILIAR DE ESTADISTICA'
 'AGRICULTORES DE CULTIVOS TRANSITORIOS' 'VENDERORA' 'MODISTERIA'
 'OFICIOS VARIOS EN SEMINARIO' 'ACOMPAÐANTES' 'COCINERA' 'CAJERA'
 'CUIDANDO ANCIANOS' 'OFICIOS  VARIOS' 'DOCENTE' 'AUXILIAR DE COBRANZA'
 'PORFESORA' 'CULTIVADORA FLORES' 'DESCONOCIDA' 'ILEGIBLE' 'SENILIDAD'
 'PELUQUEROS, ESPECIALISTAS EN TRATAMIENTOS DE BELLEZA Y AFINES'
 'OTROS TRABAJADORES DE SERVICIOS PERSONALES A PARTICULARES, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'AUX  CARTERA' 'PERSONAL DOM+STICO' 'OPERADORES DE M-QUINAS PARA COSER'
 'VENDEDORES AMBULANTES'
 'IMPRESORES DE SERICIGRAF-A Y ESTAMPADORES A LA PLANCHA Y EN TEXTILES'
 'FLORISTAS Y ARREGLISTAS FLORALES' 'ODONTËLOGOS' 'CAMPESINA' 'AMA DE CS'
 'CULTIVADORA DE FLORES' 'SERVICIOS DOMESTICOS'
 'ASEADORES Y FUMIGADORES DE OFICINAS, HOTELES Y OTROS ESTABLECIMIENTOS'
 'AMA  DE CASA' 'PSICOLOGA' 'SECRETARIOS (AS)'
 'RECOLECTORES DE MATERIAL RECICLABLE' 'ABOGADOS'
 'AUXILIARES DE SERVICIOS ESTAD-STICOS Y FINANCIEROS'
 'ACTORES Y DIRECTORES DE CINE, RADIO, TEATRO, TELEVISIËN Y AFINES'
 'AMA DE  CS' 'RECOLECTORES DE BASURA'
 'AUXILIARES DE CONTABILIDAD Y C-LCULO DE COSTOS'
 'TRABAJADORES DE HUERTAS, INVERNADEROS, VIVEROS Y JARDINES'
 'CONDUCTORES DE TAXIS' 'COMERCIANTE' 'GUARNECEDORA'
 'AGRICULTORES DE CULTIVOS PERMANENTES (PLANTACIONES DE -RBOLES Y ARBUSTOS)'
 'AUXILIAR DE DROGUERIA'
 'OPERADORES DE M-QUINAS PARA FABRICAR PRODUCTOS TEXTILES Y ART-CULOS DE PIEL Y CUERO, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'PROFESORES DE EDUCACIËN SECUNDARIA' 'INGENIEROS INDUSTRIALES Y AFINES'
 'VENDEDORES A DOMICILIO Y POR TEL+FONO'
 'BIBLIOTECARIOS, DOCUMENTALISTAS Y AFINES'
 'AUXILIARES ADMINISTRATIVOS Y AFINES'
 'SASTRES, MODISTOS COSTUREROS SOMBREREROS Y AFINES' 'PELUQUERA'
 'TRABAJADORES SOCIALES Y AFINES' 'MESEROS, TABERNEROS Y AFINES'
 'COORDINADORES Y SUPERVISORES EN MANDOS MEDIOS DE PRODUCCIËN Y OPERACIONES EN EMPRESAS P+BLICAS Y PRIVADAS, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'ENFERMEROS(AS) PROFESIONALES' 'AUXILIARES DE ENFERMER-A Y ODONTOLOG-A'
 'COCINEROS Y AFINES'
 'INGENIEROS CATASTRALES, INGENIEROS GEËGRAFOS Y AFINES' 'PSICËLOGOS'
 'OPERADORES DE M-QUINAS PARA FABRICAR PRODUCTOS DE PAPEL Y AFINES'
 'OPERADORES DE M-QUINAS PULIDORAS, GALVANIZADORAS Y RECUBRIDORAS DE METALES'
 'OTROS ARTESANOS, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'PULIDORES DE METALES Y AFILADORES DE HERRAMIENTAS' 'COMPRADORES'
 'CONTADORES' 'REPRESENTANTES COMERCIALES Y T+CNICOS DE VENTAS'
 'OFICIOS VARAIOS' 'PARTERAS'
 'AGENTES P+BLICOS Y PRIVADOS DE COLOCACIËN Y CONTRATISTAS DE MANO DE OBRA'
 'AMA  DE  CS'
 'TRABAJADORES DE LOS CUIDADOS PERSONALES Y AFINES, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'VENDEDORES EN QUIOSCOS Y PUESTOS DE MERCADO'
 'AGENTES COMERCIALES Y CORREDORES, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'ARTESANOS DE LOS TEJIDOS, EL CUERO Y MATERIALES SIMILARES'
 'RECEPCIONISTAS, EMPLEADOS DE INFORMACIËN Y SERVICIO AL CLIENTE'
 'AGENTES DE LA POLIC-A NACIONAL'
 'OTROS COORDINADORES Y SUPERVISORES EN MANDOS MEDIOS DE EMPRESAS P+BLICAS Y PRIVADAS, NO CLASIFICADAS BAJO OTROS EP-GRAFES'
 'ASISTENTES EN TRABAJO SOCIAL Y COMUNITARIO'
 'PROFESIONALES DE LA EDUCACIËN, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'ESTAD-STICOS' 'AUXILIARES DE LA POLICIA NACIONAL'
 'DIRECTORES Y GERENTES GENERALES DE EMPRESAS PRIVADAS' 'ESTUDIANTE'
 'T+CNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES EN OPERACIONES COMERCIALES, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'COORDINADORES Y SUPERVISORES DE VENTAS Y COMERCIALIZACIËN'
 'NIÐERAS Y CUIDADORAS INFANTILES'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCIËN Y OPERACIONES EN AGRICULTURA, CAZA, SILVICULTURA Y PESCA'
 'INSTRUCTORES MEDIOS DE TRANSPORTE Y AFINES'
 'DIRECTORES DE DEPARTAMENTOS DE ABASTECIMIENTO Y DISTRIBUCIËN'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCIËN Y OPERACIONES EN COMERCIO MAYORISTA Y MINORISTAS'
 'TRABAJADORES AGROPECUARIOS' 'MINEROS Y CANTEROS'
 'COORDINADORES Y SUPERVISORES FINANCIEROS Y ADMINISTRATIVOS'
 'COORDINADORES Y SUPERVISORES DE PRODUCCIËN Y OPERACIONES EN RESTAURANTES, HOT+LES, HOSPITALES Y AFINES'
 'DIRIGENTES Y ADMINISTRADORES DE ORGANIZACIONES DE EMPLEADORES, DE TRABAJADORES Y DE OTRAS DE INTER+S SOCIOECONËMICO'
 'PROFESIONALES DEL DERECHO, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'PROFESORES E INSTRUCTORES DE EDUCACIËN ESPECIAL' 'CURANDEROS'
 'LAVANDEROS Y PLANCHADORES MANUALES'
 'ALFAREROS Y AFINES (BARRO, ARCILLA Y ABRASIVOS)' 'AGRËNOMOS Y AFINES'
 'DIRECTORES DE DEPARTAMENTOS DE VENTAS Y COMERCIALIZACIËN'
 'RECEPTORES DE APUESTAS Y AFINES'
 'ESPECIALISTAS EN ORGANIZACIËN, ADMINISTRACIËN DE EMPRESAS, AN-LISIS FINANCIERO Y AFINES, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'COBRADORES Y AFINES' 'ESCULTORES, PINTORES Y AFINES' 'ESTILISTA'
 'METEORËLOGOS'
 'DIRECTORES GENERALES, DE EMPRESAS O ENTIDADES DE LA ADMINISTRACIËN P+BLICA'
 'PORTEROS , CONSERJES Y AFINES' 'ASISTENTES DE EDUCACIËN ESPECIAL'
 'T+CNICOS EN DISEÐO Y DECORADORES' 'CONSEJEROS EDUCATIVOS'
 'ESPECIALISTAS EN M+TODOS PEDAGËGICOS Y MATERIAL DID-CTICO'
 'PROFESORES DE UNIVERSIDADES Y OTROS ESTABLECIMIENTOS DE EDUCACIËN SUPERIOR'
 'DIRECTORES DE DEPARTAMENTOS FINANCIEROS Y ADMINISTRATIVOS'
 'PROFESORES DE EDUCACIËN PREESCOLAR' 'BORDADORES Y AFINES'
 'M+DICOS, PROFESIONALES EN CIENCIAS DE LA SALUD Y AFINES, NO CLASIFICADOS BAJO OTROS EP-GRAFES'
 'OPERADORES DE INSTALACIONES PARA LA FABRICACIËN DE PAPEL'
 'T+CNICOS EN PROGRAMACIËN INFORM-TICA'
 'DIRECTORES DE DEPARTAMENTOS DE PERSONAL Y DE RELACIONES LABORALES'
 'INGENIEROS EL+CTRICOS, INGENIEROS ELECTRËNICOS DE TELECOMUNICACIONES Y AFINES'
 'CONDENADA LEY 30'
 'COORDINADORES Y SUPERVISORES DE PRODUCCIËN Y OPERACIONES EN CUIDADOS PERSONALES, LIMPIEZA Y SERVICIOS SIMILARES'
 'CATADORES Y CLASIFICADORES DE ALIMENTOS Y BEBIDAS'
 'SACERDOTES Y RELIGIOSOS DE DISTINTAS DOCTRINAS'
 'JEFES DE COMUNIDADES IND-GENAS, ETNIAS ESPECIALES Y AFINES'
 'FONOAUD-OLOGOS, FISIOTERAPEUTAS Y AFINES'
 'T+CNICOS Y ASISTENTES EN FARMACIA' 'ZAPATEROS Y AFINES'
 'OPERADORES DE TELARES Y OTRAS M-QUINAS TEJEDORAS'
 'SOCIËLOGOS, ANTROPËLOGOS Y AFINES'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCIËN Y OPERACIONES EN SERVICIOS DE SALUD, EDUCACIËN Y RECREACIËN'
 'PERSONAL DE LOS SERVICIOS DE PROTECCIËN Y SEGURIDAD, NO CLASIFICADO BAJO OTROS EP-GRAFES'
 'TEJEDORES CON TELARES O DE TEJIDOS DE PUNTO Y AFINES'
 'T+CNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS EN CIENCIAS F-SICAS, QU-MICAS Y AFINES'
 'PRESTAMISTAS'
 'COORDINADORES Y SUPERVISORES DE SERVICIOS SOCIALES, EDUCACIËN Y SALUD'
 'MODELOS DE MODAS, ARTE Y PUBLICIDAD'
 'ENCARGADOS DE CONTROL DE ABASTECIMIENTOS E INVENTARIO'
 'VISITADORA M+DICA' 'AUXILIARES LAICOS DE LOS CULTOS'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCIËN Y OPERACIONES EN RESTAURANTES, HOTELES Y AFINES'
 'PANADEROS, PASTELEROS Y CONFITEROS' 'F-SICOS Y ASTRËNOMOS'
 'ESCRITORES, PERIODISTAS Y AFINES' 'EMPLEADOS DE BIBLIOTECAS Y ARCHIVOS'
 'MECANËGRAFOS, TRANSCRIPTORES DE TEXTOS Y AFINES'
 'OBREROS DE OBRAS P+BLICAS Y MANTENIMIENTO: CARRETERAS, PRESAS Y OBRAS SIMILARES'
 'PILOTOS DE AVIACIËN Y AFINES'
 'T+CNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES DE SERVICIOS FINANCIEROS, CONTABLES Y AFINES'
 'FABRICANTES Y AFINADORES DE INSTRUMENTOS MUSICALES' 'M+DICOS'
 'PERSONAL DOMÉSTICO'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCIÓN Y OPERACIONES EN COMERCIO MAYORISTA Y MINORISTAS'
 'AUXILIARES DE ENFERMERÍA Y ODONTOLOGÍA'
 'NIÑERAS Y CUIDADORAS INFANTILES'
 'INSTRUCTORES DE EDUCACIÓN VOCACIONAL ARTESANAL'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCIÓN Y OPERACIONES EN AGRICULTURA, CAZA, SILVICULTURA Y PESCA'
 'TRABAJADORES DE LOS CUIDADOS PERSONALES Y AFINES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'VENDEDORES A DOMICILIO Y POR TELÉFONO'
 'COORDINADORES Y SUPERVISORES DE SERVICIOS SOCIALES, EDUCACIÓN Y SALUD'
 'COORDINADORES Y SUPERVISORES DE PRODUCCIÓN Y OPERACIONES EN CUIDADOS PERSONALES, LIMPIEZA Y SERVICIOS SIMILARES'
 'PROFESORES DE EDUCACIÓN PRIMARIA' 'AGENTES DE LA POLICÍA NACIONAL'
 'OPERADORES DE MÁQUINAS PARA LA FABRICACIÓN DE CALZADO Y AFINES'
 'AGENTES COMERCIALES Y CORREDORES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'AUXILIARES DE CONTABILIDAD Y CÁLCULO DE COSTOS' 'VIGILANTES Y CELADORES'
 'ACOMPAÑANTES' 'PROFESORES DE EDUCACIÓN SECUNDARIA'
 'OTROS COORDINADORES Y SUPERVISORES EN MANDOS MEDIOS DE EMPRESAS PÚBLICAS Y PRIVADAS, NO CLASIFICADAS BAJO OTROS EPÍGRAFES'
 'COORDINADORES Y SUPERVISORES DE VENTAS Y COMERCIALIZACIÓN'
 'OBREROS Y PEONES AGROPECUARIOS DE LABRANZA Y DE INVERNADERO'
 'AGRICULTORES DE CULTIVOS PERMANENTES (PLANTACIONES DE ÁRBOLES Y ARBUSTOS)'
 'TÉCNICOS EN DISEÑO Y DECORADORES'
 'PERSONAL DE POMPAS FÚNEBRES Y EMBALSAMADORES' 'AGRÓNOMOS Y AFINES'
 'OTROS TRABAJADORES DE SERVICIOS PERSONALES A PARTICULARES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'PROFESORES DE EDUCACIÓN PREESCOLAR'
 'PROFESIONALES DE LA EDUCACIÓN, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'TÉCNICOS Y POSTSECUNDARIOS NO UNIVERSITARIOS EN INGENIERÍA INDUSTRIAL Y QUÍMICA INDUSTRIAL'
 'REPRESENTANTES COMERCIALES Y TÉCNICOS DE VENTAS'
 'DIRIGENTES Y ADMINISTRADORES DE ORGANIZACIONES DE EMPLEADORES, DE TRABAJADORES Y DE OTRAS DE INTERÉS SOCIOECONÓMICO'
 'PROFESIONALES DEL DERECHO, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'ECONOMISTAS'
 'OPERARIOS DE LA CONSERVACIÓN DE FRUTAS, LEGUMBRES, VERDURAS Y AFINES'
 'COORDINADORES Y SUPERVISORES DE PRODUCCIÓN Y OPERACIONES EN CONSTRUCCIÓN Y OBRAS PÚBLICAS'
 'MÚSICOS, CANTANTES Y BAILARINES CALLEJEROS, DE CABARET Y AFINES'
 'ENCUADERNADORES Y AFINES' 'SUBOFICIALES DE LA POLICÍA NACIONAL'
 'ESPECIALISTAS EN MÉTODOS PEDAGÓGICOS Y MATERIAL DIDÁCTICO'
 'LIMPIABOTAS Y OTROS TRABAJADORES CALLEJEROS'
 'PINTORES DECORADORES DE VIDRIO, CERÁMICA Y OTROS MATERIALES'
 'DIRECTORES DE DEPARTAMENTOS DE PUBLICIDAD Y DE RELACIONES PÚBLICAS'
 'COORDINADORES Y SUPERVISORES DE PRODUCCIÓN Y OPERACIONES EN APROVECHAMIENTO AGRÍCOLA, PECUARIO Y SILVÍCOLA'
 'TÉCNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES DE SERVICIOS DE ADMINISTRACIÓN, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'EMBALADORES MANUALES Y OTROS OBREROS DE LA INDUSTRIA MANUFACTURERA'
 'TÉCNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS EN INGENIERÍA CIVIL, ARQUITECTURA, AGRIMENSORES Y AFINES'
 'ARQUITECTOS, INGENIEROS Y AFINES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'TÉCNICOS Y ASISTENTES EN FARMACIA'
 'PRACTICANTES DE LA MEDICINA TRADICIONAL'
 'DIRECTORES DE DEPARTAMENTOS DE VENTAS Y COMERCIALIZACIÓN'
 'TÉCNICOS EN PROGRAMACIÓN INFORMÁTICA' 'INSPECTORES DE LA EDUCACIÓN'
 'PROFESORA' 'OBREROS DE MINAS Y CANTERAS'
 'PROFESORES E INSTRUCTORES DE EDUCACIÓN ESPECIAL'
 'JEFES DE COMUNIDADES INDÍGENAS, ETNIAS ESPECIALES Y AFINES'
 'OPERADORES DE M?QUINAS PARA FABRICAR PRODUCTOS TEXTILES Y ART?CULOS DE PIEL Y CUERO, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'PROFESORES DE EDUCACI?N SECUNDARIA' 'ANALISTAS Y AGENTES FINANCIEROS'
 'AGRICULTORES DE CULTIVOS PERMANENTES (PLANTACIONES DE ?RBOLES Y ARBUSTOS)'
 'T?CNICOS EN DISE?O Y DECORADORES' 'PROFESORES DE EDUCACI?N PRIMARIA'
 'COORDINADORES Y SUPERVISORES DE VENTAS Y COMERCIALIZACI?N'
 'VENDEDORES A DOMICILIO Y POR TEL?FONO' 'PERSONAL DOM?STICO'
 'TRABAJADORES DE LOS CUIDADOS PERSONALES Y AFINES, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'PROFESORES DE EDUCACI?N PREESCOLAR' 'INSPECTORES DE LA EDUCACI?N'
 'CAJEROS Y EXPENDEDORES DE BILLETES'
 'INSTRUCTORES DE EDUCACI?N VOCACIONAL ARTESANAL'
 'ENCARGADOS DE SERVICIOS DE APOYO A LA PRODUCCI?N'
 'REPRESENTANTES COMERCIALES Y T?CNICOS DE VENTAS' 'ELECTROT?CNICOS'
 'PESCADORES'
 'M?DICOS, PROFESIONALES EN CIENCIAS DE LA SALUD Y AFINES, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'PROFESIONALES DE LA EDUCACI?N, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'ASISTENTES DE COMERCIO EXTERIOR'
 'OTROS TRABAJADORES DE SERVICIOS PERSONALES A PARTICULARES, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'RECEPCIONISTAS, EMPLEADOS DE INFORMACI?N Y SERVICIO AL CLIENTE'
 'AGENTES COMERCIALES Y CORREDORES, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'OTROS ARTESANOS, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'T?CNICOS Y ASISTENTES EN FARMACIA'
 'AGENTES P?BLICOS Y PRIVADOS DE COLOCACI?N Y CONTRATISTAS DE MANO DE OBRA'
 'AUXILIARES DE ENFERMER?A Y ODONTOLOG?A' 'GU?AS'
 'ANALISTAS DE SISTEMAS INFORM?TICOS' 'ACOMPA?ANTES'
 'OTROS COORDINADORES Y SUPERVISORES EN MANDOS MEDIOS DE EMPRESAS P?BLICAS Y PRIVADAS, NO CLASIFICADAS BAJO OTROS EP?GRAFES'
 'T?CNICOS Y POSTSECUNDARIOS NO UNIVERSITARIOS EN MEC?NICA Y CONSTRUCCI?N MEC?NICA'
 'DIRECTORES GENERALES, DE EMPRESAS O ENTIDADES DE LA ADMINISTRACI?N P?BLICA'
 'MECAN?GRAFOS, TRANSCRIPTORES DE TEXTOS Y AFINES'
 'ARQUITECTOS, INGENIEROS Y AFINES, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'T?CNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES DE LA MEDICINA MODERNA Y LA SALUD (EXCEPTO EL PERSONAL DE PARTER?A), NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'T?CNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES DE SERVICIOS ADMINISTRATIVOS Y AFINES'
 'NI?ERAS Y CUIDADORAS INFANTILES' 'PSIC?LOGOS'
 'ASISTENTES DE ENSE?ANZA EN EDUCACI?N PREESCOLAR'
 'FIL?LOGOS, TRADUCTORES E INT?RPRETES' 'AGR?NOMOS Y AFINES'
 'COORDINADORES Y SUPERVISORES DE PRODUCCI?N Y OPERACIONES EN RESTAURANTES, HOT?LES, HOSPITALES Y AFINES'
 'PROFESORES E INSTRUCTORES DE EDUCACI?N ESPECIAL'
 'ARTESANOS DE LA MADERA Y MATERIALES SIMILARES'
 'EMPLEADOS DE SERVICIOS DE CORREO'
 'DIRECTORES DE DEPARTAMENTOS DE VENTAS Y COMERCIALIZACI?N'
 'INGENIEROS EL?CTRICOS, INGENIEROS ELECTR?NICOS DE TELECOMUNICACIONES Y AFINES'
 'OFICIALES DE LAS FUERZAS MILITARES'
 'OPERADORES DE EQUIPOS DE RADIODIFUSI?N, TELEVISI?N Y TELECOMUNICACIONES'
 'OPERARIOS DEL TRATAMIENTO DE LA MADERA'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCI?N Y OPERACIONES EN AGRICULTURA, CAZA, SILVICULTURA Y PESCA'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCI?N Y OPERACIONES EN SERVICIOS DE SALUD, EDUCACI?N Y RECREACI?N'
 'OPERADORES DE TELARES Y OTRAS M?QUINAS TEJEDORAS'
 'INGENIEROS QU?MICOS Y AFINES' 'ODONT?LOGOS'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCI?N Y OPERACIONES EN TRANSPORTE, ALMACENAMIENTO Y COMUNICACIONES'
 'T?CNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES EN OPERACIONES COMERCIALES, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'OBREROS DE ENSAMBLE'
 'COORDINADORES Y SUPERVISORES DE PRODUCCI?N Y OPERACIONES EN CUIDADOS PERSONALES, LIMPIEZA Y SERVICIOS SIMILARES'
 'DIRIGENTES Y ADMINISTRADORES DE ORGANIZACIONES DE EMPLEADORES, DE TRABAJADORES Y DE OTRAS DE INTER?S SOCIOECON?MICO'
 'DIRIGENTES Y ADMINISTRADORES DE ORGANIZACIONES HUMANITARIAS Y DE OTRAS ORGANIZACIONES ESPECIALIZADAS'
 'PRESA BUEN PASTOR'
 'JEFES DE COMUNIDADES IND?GENAS, ETNIAS ESPECIALES Y AFINES'
 'OBREROS DE PESCA, CAZA Y TRAMPA' 'TAQUILLEROS'
 'COORDINADORES Y SUPERVISORES EN MANDOS MEDIOS DE PRODUCCI?N Y OPERACIONES EN EMPRESAS P?BLICAS Y PRIVADAS, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'ACTORES Y DIRECTORES DE CINE, RADIO, TEATRO, TELEVISI?N Y AFINES'
 'DIRECTORES DE DEPARTAMENTOS DE PRODUCCI?N Y OPERACIONES EN COMERCIO MAYORISTA Y MINORISTAS'
 'COORDINADORES Y SUPERVISORES DE SERVICIOS SOCIALES, EDUCACI?N Y SALUD'
 'TRABAJADORES PECUARIOS, GANADEROS Y AFINES, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'ARQUITECTOS Y URBANISTAS' 'MATEM?TICOS Y ACTUARIOS'
 'EMPLEADOS TELEFONISTAS Y DE SERVICIOS DE INTERNET'
 'AYUDANTES EN REPARACI?N Y MEC?NICA EN GENERAL (EXCEPTO VEH?CULOS DE MOTOR)'
 'CARNICEROS, PESCADEROS Y AFINES'
 'MIEMBROS DEL PODER EJECUTIVO Y DE LOS CUERPOS LEGISLATIVOS'
 'OPERARIOS DE LA CONSERVACI?N DE FRUTAS, LEGUMBRES, VERDURAS Y AFINES'
 'T?CNICOS EN PROGRAMACI?N INFORM?TICA'
 'T?CNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES DE SERVICIOS DE ADMINISTRACI?N, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'ASISTENTES DE ENSE?ANZA EN EDUCACI?N SUPERIOR, SECUNDARIA Y PRIMARIA'
 'OPERADORES DE MÁQUINAS PARA FABRICAR PRODUCTOS TEXTILES Y ARTÍCULOS DE PIEL Y CUERO, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'RECEPCIONISTAS, EMPLEADOS DE INFORMACIÓN Y SERVICIO AL CLIENTE'
 'COORDINADORES Y SUPERVISORES EN MANDOS MEDIOS DE PRODUCCIÓN Y OPERACIONES EN EMPRESAS PÚBLICAS Y PRIVADAS, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'LIMPIADORES DE FACHADAS Y DESHOLLINADORES'
 'MÉDICOS, PROFESIONALES EN CIENCIAS DE LA SALUD Y AFINES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'OTROS ARTESANOS, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'GRABADORES DE VIDRIO' '"'
 'DIRIGENTES Y ADMINISTRADORES DE PARTIDOS POLÍTICOS'
 'PROFESIONALES DE LA INFORMÁTICA'
 'COORDINADORES Y SUPERVISORES DE PRODUCCIÓN Y OPERACIONES EN RESTAURANTES, HOTÉLES, HOSPITALES Y AFINES'
 'FONOAUDÍOLOGOS, FISIOTERAPEUTAS Y AFINES' 'ODONTÓLOGOS' 'GUÍAS'
 'TÉCNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES DE LA MEDICINA MODERNA Y LA SALUD (EXCEPTO EL PERSONAL DE PARTERÍA), NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'OBREROS DE LA CONSTRUCCIÓN DE EDIFICIOS'
 'COORDINADORES Y SUPERVISORES DE PRODUCCIÓN Y OPERACIONES EN TRANSPORTE Y COMUNICACIONES'
 'QUÍMICOS Y AFINES'
 'TÉCNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS Y ASISTENTES EN OPERACIONES COMERCIALES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'DIRECTORES GENERALES, DE EMPRESAS O ENTIDADES DE LA ADMINISTRACIÓN PÚBLICA'
 'OBREROS FORESTALES'
 'TRABAJADORES PECUARIOS, GANADEROS Y AFINES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'COORDINADORES Y SUPERVISORES DE PUBLICIDAD, INFORMACIÓN, RELACIONES PÚBLICAS Y SERVICIO AL CLIENTE'
 'CRIADORES DE GANADO Y TRABAJADORES DE LA CRÍA DE ANIMALES DOMÉSTICOS DIVERSOS'
 'OFICIALES Y OPERARIOS DE LA CONSTRUCCIÓN Y AFINES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'OPTÓMETRAS'
 'ESPECIALISTAS EN ORGANIZACIÓN, ADMINISTRACIÓN DE EMPRESAS, ANÁLISIS FINANCIERO Y AFINES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'OTROS DIRECTORES DE DEPARTAMENTOS, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'TÉCNICOS E HIGIENISTAS DENTALES' 'TÉCNICOS Y ASISTENTES VETERINARIOS'
 'ESTADÍSTICOS'
 'AGENTES DE LA ADMINISTRACIÓN PÚBLICA EN ADUANAS, IMPUESTOS Y AFINES, NO CLASIFICADOS BAJO OTROS EPÍGRAFES'
 'COREÓGRAFOS Y BAILARINES'
 'T?CNICOS, POSTSECUNDARIOS NO UNIVERSITARIOS EN CIENCIAS F?SICAS, QU?MICAS Y AFINES'
 'ESPECIALISTAS EN ORGANIZACI?N, ADMINISTRACI?N DE EMPRESAS, AN?LISIS FINANCIERO Y AFINES, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'OPERADORES DE INSTALACIONES DE PROCESAMIENTO DE MINERALES Y ROCAS'
 'AGENTES DE LA POLIC?A NACIONAL' 'NUTRICIONISTAS Y DIETISTAS'
 'ENSAMBLADORES DE PRODUCTOS DE CART?N, TEXTILES Y MATERIALES AFINES'
 'PERSONAL DE SERVICIO A PASAJEROS' 'M?DICOS VETERINARIOS Y ZOOTECNISTAS'
 'ESPECIALISTAS EN CIENCIAS ECONOMICAS SOCIALES Y HUMANAS, NO CLASIFICADOS BAJO OTROS EP?GRAFES'
 'AUXILIARES DE CONTABILIDAD Y C?LCULO DE COSTOS'
 'PATRONISTAS, CORTADORES DE TELA, CUERO Y AFINES'
 'OPERARIOS DE LA ELABORACI?N DE PRODUCTOS L?CTEOS'
 'OBREROS DE LA CONSTRUCCI?N DE EDIFICIOS'
 'OPERADORES DE M?QUINAS PARA COSER' 'ALBA?ILES, MAMPOSTEROS Y AFINES'
 'OPERARIOS DE LA FOTOGRAF?A Y AFINES'
 'DIRECTORES DE REGIONALES, SUCURSALES, OFICINAS Y AFINES DE LA ADMINISTRACI?N P?BLICA'
 'COORDINADORES Y SUPERVISORES DE PRODUCCI?N Y OPERACIONES EN APROVECHAMIENTO AGR?COLA, PECUARIO Y SILV?COLA'
 'EBANISTAS Y AFINES'

Codificar sexo, estado civil y nivel educativo

In [115]:
sex = {
    '1': 'Mascuilino',
    '2': 'Femenino',
    '3': 'Indeterminado'
}

estado_civil = {
    '1': 'Soltero', 
    '2': 'Casado',
    '3': 'Viudo',
    '4': 'Unión Libre, divorciado, otro',
    '5': 'Sin información'
}

educacion = {
    '1': 'Preescolar',
    '2': 'Primaria',
    '3': 'Secundaria',
    '4': 'Superior',
    '5': 'Ninguno',
    '9': 'Sin información'
}

# muerteocupacion = {
#     '1': 'Si',
#     '2': 'No',
#     '9': 'Sin información'

# }

simuerteocupacion = {
    '1': 'Accidente de tránsito',
    '2': 'Enfermedad profesional',
    '9': 'Sin información'
}

grupo_edad = {
    '10': '15-19',
    '11': '20-24',
    '12': '25-29',
    '13': '30-34',
    '14': '35-39',
    '15': '40-44',
    '16': '45-49',
    '17': '50-54',
    '18': '55-59',
    '19': '60-64',
    '20': '65-69',
    '21': '70-74',
    '22': '75-79',
    '23': '80-84',
    '24': '85 y más',
    '25': 'Edad desconocida'
}

Realizamos las respectivas transformaciones

In [116]:
# Las variables deben ser de tipo str
data['SEXO'] = data['SEXO'].astype(str)
data['EST_CIVIL'] = data['EST_CIVIL'].astype(str)
data['NIVEL_EDU'] = data['NIVEL_EDU'].astype(str)
# data['MUERTEPORO'] = data['MUERTEPORO'].astype(str)
data['SIMUERTEPO'] = data['SIMUERTEPO'].astype(str)
data['GRU_ED1'] = data['GRU_ED1'].astype(str)

In [117]:
#Mapeamos las variables
data['SEX'] = data16['SEXO'].map(sex)
data['ESTADO_CIVIL'] = data['EST_CIVIL'].map(estado_civil)
data['NIVEL_EDUCACION'] = data['NIVEL_EDU'].map(educacion)
# data['MUERTE_POR_OCUPACION'] = data['MUERTEPORO'].map(muerteocupacion)
data['SIMUERTE_POR_OCUPACION'] = data['SIMUERTEPO'].map(simuerteocupacion)
data['GRUPO_ETARIO'] = data['GRU_ED1'].map(grupo_edad)

Organizamos las variables

In [118]:
columnas = ['SEXO', 'SEX', 'EST_CIVIL', 'ESTADO_CIVIL', 'NIVEL_EDU', 'NIVEL_EDUCACION', 'SIMUERTEPO', 'SIMUERTE_POR_OCUPACION', 'GRU_ED1', 'GRUPO_ETARIO']
columnas_quedan = [col for col in data16.columns if col not in columnas]
data = data[columnas_quedan + columnas]

Transformación de fecha de defunción

In [119]:
missing_count = data16['MES'].isna().sum()
print(f"Number of missing values in MES: {missing_count}")

Number of missing values in MES: 0

In [120]:
data['ANO'] = pd.to_numeric(data['ANO'], errors='coerce')
data['MES'] = pd.to_numeric(data['MES'], errors='coerce')

# Convertir los NaN en mes 12
data['MES'] = data['MES'].fillna(12).astype(int)
data['ANO'] = data['ANO'].astype(int)
data['MES'] = data['MES'].astype(int)

# Crear 'FECHA' 
data['FECHA'] = pd.to_datetime(data['ANO'].astype(str) + '-' + data['MES'].astype(str)).dt.to_period('M')
display(HTML(data[['ANO', 'MES', 'FECHA']].head(10).to_html()))

Organizar el dataframe

In [121]:
del data['GRU_ED2']
del data['GRU_ED1']

In [126]:
columnas = ['ANO', 'MES', 'FECHA'] + [col for col in data.columns if col not in ['ANO', 'MES', 'FECHA']]
columnas = [col for col in data.columns if col not in ['COD_INST', 'NOM_INST','OCUPACION']] + ['COD_INST', 'NOM_INST','OCUPACION']
data = data[columnas]
display(HTML(data.head(10).to_html()))

Decodificación de otras variables

In [127]:
etnia_dict ={
    '1': 'Indígena',
    '2': 'Rom (Gitano)',
    '3': 'Raizal del archipielago de San Andres y Providencia',
    '4': 'Palenquero de San Basilio',
    '5': 'Negro(a), mulato(a), afrocolombiano(a) o afrodescendiente',
    '6': 'Ninguno de las anteriores',
    '9': 'Sin información'
}

seg_social_dict = {
    '1': 'Contributivo',
    '2': 'Subsidiado',
    '3': 'Vinculado',
    '4': 'Particular',
    '5': 'Otro',
    '6': 'Ignorado',
    '9': 'Sin información'
}

administradoradesalud_dict = {
    '1': 'Entidad promotora de salud',
    '2': 'Entidad promotora de salud - Subsidiado',
    '3': 'Entidad adaptada de salud',
    '4': 'Entidad especial de salud',
    '5': 'Entidad exceptuada de salud',
    '9': 'Sin información'
}

manera_muerte_dict = {
    "1": "Natural",
    "2": "Violenta",
    "3": "En estudio"
}

asistencia_medica_dict = {
    "1": "Sí",
    "2": "No",
    "3": "Ignorado",
    "4": "Sin información"
}

area_residencia_dict = {
    "1": "Cabecera municipal",
    "2": "Centro poblado (Inspección, corregimiento o caserío)",
    "3": "Rural disperso",
    "9": "Sin información"
}

#### Mapeamos las variables codificadas

In [128]:
# Las variables deben ser de tipo str
data['IDPERTET'] = data['IDPERTET'].astype(str)
data['AREA_RES'] = data['AREA_RES'].astype(str)
data['SEG_SOCIAL'] = data['SEG_SOCIAL'].astype(str)
data['PMAN_MUER'] = data['PMAN_MUER'].astype(str)
data['ASIS_MED'] = data['ASIS_MED'].astype(str)

In [129]:
#Mapeamos las variables
data['ETNIA'] = data['IDPERTET'].map(etnia_dict)
data['AREA DE RESIDENCIA'] = data['AREA_RES'].map(area_residencia_dict)
data['SEGURIDAD SOCIAL'] = data['SEG_SOCIAL'].map(seg_social_dict)
# data['MUERTE_POR_OCUPACION'] = data['MUERTEPORO'].map(muerteocupacion)
data['PROBABLE MANERA DE MUERTE'] = data['PMAN_MUER'].map(manera_muerte_dict)
data['ASISTENCIA MEDICA PREVIO A MUERTE'] = data['ASIS_MED'].map(asistencia_medica_dict)

#### Observamo las comorbilidades

In [130]:
columnas = ['CAUSA_666', 'CAUSA_667', 'C_DIR12', 'C_ANT22', 'C_ANT12', 'C_DIR12', 'C_MUERTEE', 'C_MUERTED', 'C_MUERTEC', 'C_MUERTEB', 'C_MCM1', 'C_ANT32', 'C_PAT2', 'C_PAT1', 'C_ANT3', 'C_ANT2', 'C_ANT1', 'C_DIR1', 'C_MUERTE']
unicos = {}

for col in columnas:
    valores_unicos = data[col].unique()
    unicos[col] = valores_unicos.tolist()
print("Valores únicos de las variables:")
for col, valores in unicos.items():
    print(f"{col}: {valores}")
    # print(f'{col} tiene {len(data[col])} valores únicos')
    

# data[['CAUSA_666', 'CAUSA_667', 'C_DIR12', 'C_ANT22', 'C_ANT12', 'C_DIR12', 'C_MUERTEE', 'C_MUERTED', 'C_MUERTEC', 'C_MUERTEB', 'C_MCM1', 'C_ANT32', 'C_PAT2', 'C_PAT1', 'C_ANT3', 'C_ANT2', 'C_ANT1', 'C_DIR1', 'C_MUERTE']].head(100)

Valores únicos de las variables:
CAUSA_666: ['', '209', '209.0']
CAUSA_667: ['', '207.0', '207']
C_DIR12: ['', 'C798', 'C539', 'R092', 'I509', 'D489', 'N939', 'R688', 'C787', 'C780', 'N390', 'E878', 'D649', 'R090', 'D62', 'R571', 'N19', 'K729', 'A499', 'C794', 'J189', 'C795', 'I469', 'E872', 'C785', 'C793', 'C786', 'J989', 'C809', 'G039', 'C781', 'J81', 'J984', 'R570', 'L089', 'K632', 'C790', 'Y95', 'I219', 'G934', 'R572', 'I499', 'C788', 'K650', 'Z491', 'R578', 'C799', 'C791', 'A419', 'J969', '"', 'N133', 'E46', 'Z492', 'C783', 'B961', 'I269', 'R104', 'J150', 'E43', 'K603', 'J960', 'N760', 'K922', 'C782', 'I260', 'E86']
C_ANT22: ['', 'C80', 'C798', 'E875', 'K719', 'C780', 'C782', 'N138', 'C795', 'I469', 'K659', 'C793', 'C539', 'K631', 'N180', 'Z936', 'K625', 'I10', 'J984', 'A09', 'C787', 'N390', 'A419', 'R18', 'G938', 'R58', 'T08', 'Z988', 'D70', 'Y95', 'Z511', 'K638', 'Z491', 'L988', 'E86', 'I269', 'N133', 'N19', 'J869', 'C791', 'K603', 'Z730', 'C530', 'C781', 'C790', 'C809', 'C786', 'N139', 'C785', 'E149', 'L899', 'Z510', 'E109', 'N825', 'K650', 'N739', 'D849', 'C788', 'E43', 'J988', 'C799', 'Z492', 'C797', 'D471', 'D489', 'I619', 'K921', 'J189', 'L089', 'N939', 'N858', 'Z933', 'D649', '"', 'N938', 'Z98', 'E46', 'I739', 'R13', 'N368', 'D619', 'R090', 'C519', 'T730', 'K566', 'J180', 'C52', 'C55', 'C531', 'G049', 'R572', 'Z905', 'G934', 'R630', 'J690', 'K658', 'N823', 'I251', 'N820', 'Z940']
C_ANT12: ['', 'C793', 'Y95X', 'C791', 'C786', 'C539', 'I509', 'N189', 'K631', 'C80', 'Y95', 'C790', 'C787', 'C780', 'Z950', 'C788', 'D649', 'C795', 'J984', 'N19', 'D489', 'R630', 'K566', 'R571', 'R090', 'K628', 'R570', 'M844', 'C229', 'C798', 'R688', 'N390', 'C349', 'N139', 'J81', 'C792', 'R54', 'K650', 'Z491', 'Z511', 'B379', 'C785', 'K564', 'N829', 'I619', 'M993', 'C809', 'N133', 'Z510', 'C781', 'N939', 'K830', 'N739', 'E875', 'G934', 'C799', 'C797', 'K593', 'D509', 'R572', 'T827', 'C189', 'N135', 'D849', 'Z940', 'C782', 'N289', 'L089', 'J189', 'A419', 'C771', 'N859', '"', 'K746', 'R579', 'A498', 'C779', 'L899', 'Z492', 'R578', 'L984', 'C52', 'K831', 'G952', 'B49', 'C210', 'J180', 'E86', 'C794', 'Z933', 'Z988', 'S320', 'T509', 'B377', 'N138', 'Z466', 'I803', 'Z515', 'E43', 'Z911', 'I822', 'C839', 'N322', 'A499', 'E889']
C_MUERTEE: ['', '1', '"', '1.0']
C_MUERTED: ['', '1', '"', '1.0']
C_MUERTEC: ['', '1', '"', '1.0']
C_MUERTEB: ['', '1', '"', '1.0']
C_MCM1: ['', 'C539', 'C538', '"', 'C530']
C_ANT32: ['', 'C539', 'C55', 'C80', 'D649', 'C798', 'C780', 'C795', 'Z511', 'A309', 'L89', 'B977', 'B879', 'G938', 'C782', 'Z436', 'D849', 'N823', 'K639', 'C785', 'N361', 'Y95', 'Z510', 'N19', 'J984', 'C788', 'C790', 'C787', 'N039', 'D487', 'E877', 'C791', 'C786', 'C189', 'K628', 'C509', 'I10', 'N820', 'I119', 'C799', 'Z988', 'C793', 'C530', 'C783', 'D809', 'I420', '"', 'J988', 'F03', 'C499', 'Z491', 'J189', 'K650', 'C56', 'C784', 'N189', 'A419', 'K604', 'R263', 'R02', 'E46', 'I351', 'D489', 'C259', 'E149', 'E86', 'I469', 'Z515']
C_PAT2: ['', 'M329', 'E46X', 'N390', 'R64X', 'N189', 'B199', 'T66X', 'I719', 'K831', 'C539', 'C795', 'N133', '0', 'C798', 'R11X', 'R785', 'Z511', 'N739', 'I269', 'J841', 'D649', 'K830', 'I694', 'C780', 'I829', 'S729', 'I10X', 'K922', 'C787', 'Y95X', 'J449', 'J189', 'C80X', 'E46', 'C509', 'D329', 'Z510', 'M726', 'I10', 'K319', 'E119', 'K509', 'E880', 'M623', 'I219', 'K279', 'I871', 'E149', 'N139', 'I120', 'N19', 'I679', 'C782', 'G309', 'E872', 'R17', 'I509', 'N179', 'C80', 'L89', 'D489', 'S720', 'Z491', 'C531', 'R568', 'Z988', 'C793', 'I251', 'I740', 'Z933', 'N180', 'E146', 'N138', 'C786', 'N289', 'C785', 'I698', 'C189', 'I313', 'N859', 'E109', 'K769', 'E43', 'M199', 'S129', 'D689', 'K729', 'I499', 'C20', 'Z936', 'R688', 'R601', 'I64', 'I500', 'R18', 'N823', 'S423', 'K632', 'E875', 'C169', 'G938', 'D849', 'E059', 'D539', 'C791', 'C56', 'C710', 'N039', 'F03', 'A419', 'C809', 'J969', 'L899', 'Z436', 'I802', 'A90', 'I351', 'M139', 'E039', 'I619', 'D487', 'F102', 'C792', 'I822', 'K566', 'C799', 'D508', 'I669', 'I489', 'E86', 'C790', 'M069', 'E876', 'Z911', 'G934', 'M844', 'N185', 'I471', 'I482', 'N209', 'D619', 'C541', 'L089', 'E440', 'D509', 'E878', 'I209', 'I349', 'E871', 'Z730', 'T913', 'R263', '"', 'M169', 'R609', 'C794', 'K746', 'R97', 'R58', 'E849', 'N939', 'E780', 'K649', 'E142', 'G629', 'R572', 'I959', 'A415', 'E669', 'K590', 'K560', 'A099', 'C781', 'I119', 'Z991', 'Z940', 'R000', 'C859', 'G060', 'K639', 'C779', 'K659', 'C449', 'R060', 'B24', 'F209', 'G610', 'E213', 'F192', 'N135', 'N321', 'I272', 'A499', 'E785', 'F172', 'E040', 'Z959', 'K318', 'N134', 'R11']
C_PAT1: ['', 'E439', 'N189', 'D649', 'M009', 'C539', 'N179', 'A09X', 'I10X', 'J449', 'I210', 'N823', 'I509', 'N19X', 'M819', 'D64X', 'E149', 'J189', 'G009', 'L905', 'N180', 'I771', 'I679', 'D539', 'K920', 'C80X', 'E162', 'E119', 'E46X', 'E039', 'L089', 'J90X', 'J42X', 'K566', 'J181', 'J984', 'I270', 'K922', 'N133', 'S720', 'C780', 'M069', 'R64X', 'A060', 'N390', 'E440', 'I469', 'A46X', 'I669', 'K279', 'E835', 'I500', 'C189', 'E86X', 'E43X', 'R54X', 'G409', 'A419', 'I872', 'A162', 'F209', 'C795', 'D349', 'I829', 'C798', 'F03X', 'E069', 'R568', 'N139', 'L984', 'Y950', 'E230', 'J459', 'I890', 'C787', 'K311', 'I269', 'I633', 'T474', 'I517', 'J448', 'I820', 'C579', 'J81X', 'K297', 'I110', 'J180', 'K746', 'D65X', 'E45X', 'I64X', 'G20X', 'E115', 'K659', 'K290', 'I828', 'K295', 'I498', 'R630', 'C785', 'T811', 'K802', 'K604', 'R58X', 'I259', 'E878', 'N822', 'I809', 'F790', 'K275', 'I694', 'I99X', 'F329', 'I48X', 'E42X', 'N12X', 'I119', 'C762', 'E232', 'N819', 'K831', 'C790', 'G934', 'I251', 'J969', 'M062', 'J40X', 'I609', 'M349', 'K420', 'C791', 'M199', 'K259', 'N200', 'E107', 'K628', 'I802', 'M844', 'R17X', 'F322', 'F059', 'R53X', 'E669', 'D509', 'J439', 'Y95X', 'I279', 'A418', 'M329', 'B378', 'C793', 'I129', 'D70X', 'Z936', 'D469', 'Z518', 'R18X', 'I499', 'K559', 'A499', 'E780', 'K590', 'C530', 'S729', 'I120', 'K460', 'K429', 'G309', 'T12X', 'I803', 'A563', 'K611', 'I250', 'I959', 'C509', 'I313', 'L022', 'K729', 'C796', 'L89X', 'K299', 'I619', 'Z950', 'K294', 'E870', 'J931', 'L033', 'D619', 'F319', 'I712', 'N321', 'N939', 'K632', 'K274', 'I219', 'A488', 'A044', 'A199', 'R104', 'K769', 'K810', 'C099', 'D529', 'F069', 'C788', 'E872', 'K319', 'N309', 'E109', 'C794', 'I618', 'N289', 'R599', 'N322', 'K750', 'J849', 'I692', 'I429', 'Z436', 'N949', 'M541', 'T730', 'K269', 'E050', 'R601', 'M869', 'C679', 'D62X', 'I698', 'I490', 'D689', 'E875', 'D849', 'I749', 'I501', 'M169', 'E142', 'I139', 'I678', 'B029', 'R02X', 'E41X', 'D219', 'B59X', 'G825', 'J690', 'E146', 'A170', 'I709', 'C782', 'Z988', 'T652', 'Z510', 'R100', 'N820', 'D430', 'I059', 'C786', 'I639', 'C531', 'J960', 'E059', 'D489', 'E112', 'B019', 'J80X', 'N879', 'I714', 'K650', 'I248', 'N719', 'N138', 'C56X', 'B24X', 'D519', 'N760', 'Z512', 'T66X', 'Z491', 'D648', 'G700', 'I743', 'C169', 'K409', 'E785', 'D688', 'F102', 'N159', 'C180', 'E889', 'E441', 'K631', 'D696', 'F172', 'J841', 'G959', 'N829', 'I850', 'E876', 'B909', 'T740', 'E049', 'J628', 'I674', 'C819', 'K254', 'I272', 'T142', 'T857', 'N739', 'K579', 'D500', 'E248', 'K625', 'M139', 'F191', 'R160', 'E668', 'J988', 'M478', 'E880', 'Z930', 'L080', 'R739', 'K801', 'K768', 'E249', 'T093', 'I671', 'C249', 'G419', 'C480', 'E649', 'B572', 'G938', 'I10', 'I340', 'N039', 'E46', 'K550', 'N19', 'J80', 'E43', 'J81', 'R571', 'N360', 'E45', 'D62', 'I801', 'A539', 'C20', 'K512', 'L89', 'I871', 'S097', 'R64', 'C80', 'I745', 'D694', 'K639', 'N736', 'R529', 'D471', 'D508', 'E871', 'B018', 'M623', 'I64', 'N009', 'Y95', 'G400', 'Z730', 'B24', 'R688', 'C783', 'R634', 'J440', 'K439', 'R54', 'E41', 'I420', 'R609', 'G728', 'R02', 'I821', 'I519', 'R14', 'C449', 'C56', 'N361', 'K520', 'N399', 'I830', 'E459', 'B852', 'M470', 'E145', 'E86', 'N329', 'E789', 'C349', 'G952', 'F179', 'K529', 'C260', 'F799', 'N188', 'B269', 'N948', 'R579', 'G20', 'F03', 'R18', 'D510', 'R17', 'S528', 'H913', 'K318', 'G911', 'R99', 'A157', 'K819', 'R570', 'C779', 'K222', 'I739', 'D069', 'G35', 'A09', 'M170', 'D618', 'A090', 'F79', 'D728', 'I489', 'C809', 'Z954', 'R098', 'C73', 'K904', 'F058', 'Z492', 'Z966', 'E169', 'Z896', 'I99', 'N029', 'D65', 'C799', 'R11', 'R263', 'E883', 'A099', 'N185', 'C23', 'R55', 'L023', 'B54', 'K573', 'N319', 'I620', 'I839', 'R13', 'I730', 'A529', 'L97', 'Q602', 'D369', 'L899', 'D439', 'N811', 'D487', 'S423', 'C55', 'D259', 'I889', 'J159', 'G401', '"', 'I200', 'D70', 'D061', 'E778', 'K250', 'I693', 'M879', 'K578', 'I516', 'K403', 'G301', 'C52', 'K627', 'R509', 'J441', 'K805', 'E42', 'E213', 'Z934', 'E035', 'I471', 'I249', 'L031', 'R060', 'S721', 'R572', 'F419', 'I879', 'N151', 'C538', 'E849', 'F192', 'C719', 'J42', 'N183', 'C541', 'C210', 'Z636', 'R98', 'M512', 'C519', 'Z515']
C_ANT3: ['', 'I48X', 'C539', 'E149', 'I469', 'C783', 'C80X', 'N189', 'I509', 'R02X', 'C786', 'D649', 'J689', 'E43X', 'C780', 'E440', 'E878', 'A419', 'C787', 'J180', 'N19X', 'K922', 'E86X', 'E46X', 'J969', 'I64X', 'L905', 'R578', 'J449', 'N138', 'N321', 'J698', 'C785', 'E059', 'J81X', 'T658', 'T451', 'R53X', 'N133', 'N739', 'T730', 'E119', 'I10X', 'B977', 'I709', 'K631', 'C795', 'R092', 'I803', 'I829', 'N823', 'J189', 'K920', 'N390', 'I500', 'I259', 'N049', 'D539', 'D487', 'N879', 'D70X', 'J90X', 'A09X', 'K566', 'I219', 'K729', 'C790', 'C798', 'G039', 'C788', 'J439', 'K638', 'R568', 'C793', 'N139', 'C796', 'X539', 'E42X', 'N179', 'J960', 'N939', 'C538', 'C55X', 'D619', 'D689', 'N329', 'D849', 'I802', 'K297', 'N732', 'R64X', 'J329', 'R090', 'T652', 'I420', 'N135', 'E669', 'K550', 'C530', 'R31X', 'Z988', 'J159', 'R18X', 'K579', 'E871', 'C419', 'L89X', 'J984', 'C794', 'C20X', 'Y95X', 'R630', 'I878', 'I251', 'R571', 'N72X', 'C779', 'K625', 'I749', 'G934', 'C791', 'A162', 'G20X', 'N821', 'C792', 'I269', 'I349', 'T819', 'C349', 'K85X', 'I99X', 'C710', 'D489', 'I519', 'E539', 'M844', 'K589', 'N829', 'M189', 'N180', 'E143', 'D259', 'C762', 'E668', 'C531', 'E45X', 'R17X', 'S720', 'A169', 'D62X', 'E41X', 'K431', 'K767', 'R54X', 'D414', 'N131', 'R570', 'D464', 'D469', 'J181', 'I19X', 'N188', 'Z907', 'I110', 'K604', 'M199', 'I678', 'R688', 'J939', 'N289', 'K659', 'Z510', 'C439', 'Z511', 'I313', 'I119', 'I694', 'E142', 'N132', 'N949', 'R074', 'I10', 'E46', 'N398', 'T175', 'G919', 'C80', 'I429', 'R739', 'C782', 'N039', 'K564', 'Z936', 'B978', 'E43', 'C56', 'Z512', 'D688', 'K632', 'R31', 'N888', 'Y95', 'C449', 'N308', 'I514', 'K766', 'E45', 'N828', 'N709', 'E161', 'K639', 'D483', 'N19', 'C55', 'K627', 'S097', 'D260', 'K900', 'D62', 'N361', 'B344', 'A09', 'I64', 'E41', 'E340', 'J80', 'D390', 'L511', 'R02', 'D430', 'D376', 'M339', 'L089', 'L984', 'D27', 'E875', 'Z933', 'J81', 'N322', 'K912', 'Z730', 'R54', 'R100', 'R18', 'D369', 'I879', 'N159', 'N320', 'A499', 'K746', 'R53', 'R600', 'C763', 'H913', 'G724', 'R99', 'I518', 'C383', 'K265', 'K269', 'S721', 'D648', 'C809', 'A498', 'K650', 'A090', 'I679', 'D759', 'C579', 'G936', 'I743', 'M069', 'I771', 'G938', 'E872', 'C509', 'R572', 'E039', 'Z433', 'I482', 'D70', 'J690', 'N72', 'C799', 'J929', 'G911', 'M600', 'K529', 'C169', 'N185', 'C541', 'L899', 'Z491', 'I809', 'I739', 'I46', 'B99', 'C20', 'R104', 'K805', 'I489', '"', 'I959', 'R33', 'F179', 'E162', 'R55', 'D072', 'E876', 'M519', 'L031', 'K318', 'C800', 'C259', 'E778', 'D696', 'B370', 'H269', 'N719', 'K520', 'I629', 'D374', 'R522', 'I872', 'D693', 'A099', 'N824', 'R609', 'R17', 'I99', 'I742', 'I340', 'C189', 'Z436', 'C781', 'E789', 'E86', 'Z541', 'R98', 'R64', 'R060', 'K565', 'F058']
C_ANT2: ['', 'I694', 'C530', 'C539', 'C538', 'D649', 'N19X', 'E872', 'E149', 'J81X', 'K254', 'C80X', 'N821', 'I829', 'C780', 'J449', 'A09X', 'C793', 'N139', 'C790', 'C787', 'K566', 'E43X', 'N133', 'N739', 'N189', 'R99X', 'N289', 'E46X', 'I669', 'E878', 'D65X', 'C798', 'I500', 'I10X', 'L023', 'N179', 'J969', 'R18X', 'I469', 'K631', 'L089', 'I279', 'I270', 'C181', 'C786', 'L539', 'C785', 'C795', 'I802', 'I110', 'E86X', 'I219', 'I749', 'N939', 'D759', 'S321', 'R31X', 'K659', 'R570', 'A418', 'C449', 'K920', 'L905', 'J960', 'I509', 'K928', 'A419', 'R64X', 'N180', 'I517', 'N390', 'J180', 'G939', 'R600', 'E119', 'I709', 'E110', 'J459', 'I678', 'D64X', 'J189', 'I609', 'J42X', 'R688', 'C788', 'C349', 'R601', 'R100', 'I420', 'K265', 'K650', 'K550', 'J90X', 'C791', 'I269', 'N823', 'B570', 'I64X', 'K578', 'C797', 'E147', 'I698', 'D62X', 'N824', 'C55X', 'I679', 'I313', 'N938', 'I119', 'D849', 'E789', 'X539', 'R571', 'K922', 'R02X', 'N72X', 'T941', 'C750', 'N879', 'K295', 'G935', 'R922', 'Z436', 'D539', 'I519', 'J980', 'K560', 'I48X', 'N138', 'J860', 'N829', 'R568', 'C740', 'K604', 'Y95X', 'C782', 'K669', 'C482', 'D489', 'Y838', 'R58X', 'M819', 'R54X', 'S328', 'D696', 'K628', 'D689', 'N131', 'I99X', 'L903', 'K275', 'D281', 'D619', 'N12X', 'C762', 'K529', 'I501', 'K638', 'K520', 'N321', 'A169', 'G936', 'N888', 'N859', 'A630', 'C679', 'O96X', 'L89X', 'D694', 'B977', 'C783', 'C794', 'A162', 'R092', 'E42X', 'D372', 'R090', 'N393', 'Z932', 'J984', 'J80X', 'J181', 'C56X', 'N361', 'D440', 'X795', 'J690', 'K661', 'S318', 'I890', 'K37X', 'D509', 'K729', 'K746', 'R190', 'L984', 'I891', 'T730', 'I059', 'N399', 'I809', 'I674', 'C189', 'K515', 'G931', 'N921', 'N930', 'R402', 'E162', 'I499', 'I251', 'D487', 'Z988', 'T455', 'J439', 'K766', 'C419', 'N719', 'K639', 'W939', 'G241', 'A499', 'R048', 'I620', 'E142', 'C65X', 'E875', 'F329', 'M623', 'T175', 'C509', 'Y189', 'A480', 'L988', 'R33X', 'I200', 'K251', 'R609', 'K625', 'R80X', 'N820', 'S379', 'C439', 'S469', 'K904', 'R630', 'R060', 'C499', 'D500', 'D70X', 'E340', 'M339', 'N760', 'E148', 'J941', 'D699', 'N119', 'K921', 'N209', 'R34X', 'F03X', 'D683', 'J700', 'K802', 'M189', 'D369', 'C531', 'I248', 'E778', 'G932', 'S720', 'E871', 'E835', 'K627', 'C709', 'A049', 'D260', 'I820', 'I801', 'N135', 'R11X', 'N322', 'G934', 'D377', 'C763', 'K632', 'G060', 'K805', 'N391', 'I803', 'J209', 'E45X', 'R53X', 'T353', 'K703', 'D688', 'C859', 'K750', 'I471', 'E41X', 'N059', 'R068', 'E785', 'J988', 'K279', 'K259', 'C781', 'R578', 'C778', 'K564', 'N159', 'I771', 'T092', 'Z936', 'C792', 'R633', 'T179', 'R221', 'N039', 'N825', 'D469', 'R579', 'M844', 'J689', 'Z512', 'K565', 'D479', 'C819', 'F209', 'N309', 'M869', 'Z511', 'N178', 'I742', 'C639', 'N819', 'E638', 'E889', 'R55X', 'K291', 'G919', 'T814', 'K658', 'Z491', 'G20X', 'N822', 'M726', 'K851', 'Z923', 'J869', 'E870', 'N304', 'E440', 'R042', 'J82X', 'I319', 'N111', 'K831', 'N857', 'D419', 'E876', 'F059', 'K859', 'E874', 'K439', 'A199', 'L029', 'E45', 'C80', 'E43', 'N736', 'N19', 'N290', 'E46', 'Z933', 'R58', 'X936', 'K318', 'Z938', 'E86', 'I209', 'A09', 'R11', 'J81', 'E41', 'I959', 'M069', 'J80', 'I10', 'N12', 'T857', 'I259', 'L080', 'C55', 'J940', 'N72', 'B379', 'K769', 'E880', 'L039', 'C229', 'K222', 'L89', 'Y95', 'G98', 'R53', 'R599', 'J441', 'C739', 'I260', 'K767', 'J90', 'D019', 'Z730', 'R529', 'R18', 'G938', 'R960', 'R54', 'I99', 'J939', 'R31', 'I879', 'G629', 'I516', 'Z907', 'T66', 'N308', 'I249', 'N858', 'I48', 'K611', 'R98', 'K296', 'C348', 'R160', 'R02', 'J852', 'T810', 'C220', 'E782', 'I714', 'G409', 'K719', 'D66', 'D62', 'N328', 'J150', 'I822', 'C341', 'N732', 'E40', 'R224', 'T889', 'I619', 'I490', 'G959', 'E144', 'D391', 'Z930', 'D374', 'A409', 'C779', 'I64', 'J159', 'I878', 'N301', 'N10', 'I978', 'A412', 'D060', 'C770', 'R509', 'R418', 'C412', 'K811', 'Z966', 'R001', 'D70', 'M866', 'N735', 'D441', 'R13', 'N136', 'J042', 'D069', 'B24', 'D529', 'I312', 'C784', 'B370', 'A165', 'I498', 'N170', 'K823', 'F069', 'N132', 'L899', 'C809', 'A090', 'D591', 'R104', 'J841', 'D648', 'D483', 'Z978', 'K909', 'C772', 'K579', 'N288', 'D381', 'A498', 'C799', 'A099', 'R99', 'R572', 'M868', 'N185', 'F29', 'G589', 'R263', 'J851', 'Z982', 'N359', 'E883', 'D383', 'N26', 'Z510', 'T888', 'N948', 'D65', 'I739', 'M139', 'I482', 'M541', 'C921', 'B169', 'C710', 'N009', 'D329', 'C487', 'C259', 'N733', 'L033', 'C480', 'R64', 'G301', 'S729', 'C164', 'E039', 'R634', 'J961', '"', 'C20', 'G309', 'K660', 'L893', 'D27', 'N151', 'N200', 'G009', 'C929', 'I743', 'K280', 'N312', 'Z492', 'K221', 'K20', 'K633', 'G969', 'N319', 'R17', 'I859', 'E15', 'G122', 'B029', 'K830', 'N710', 'N324', 'D610', 'G08', 'C900', 'G92', 'I871', 'N762', 'K269', 'M199', 'N130', 'C800', 'R522', 'K521', 'B572', 'C56', 'T859', 'A415', 'L022', 'B49', 'C519', 'R32']

#### Unimos la referencia de cada comorbilidad

In [131]:
# Rellenar hacia adelante las columnas con valores faltantes
enfermedades[['CODIGO', 'DESRIPCION CATEGORIAS DE TRES CARACTERES']] = enfermedades[['CODIGO', 'DESRIPCION CATEGORIAS DE TRES CARACTERES']].ffill()
enfermedades.head()

,CODIGO,DESRIPCION CATEGORIAS DE TRES CARACTERES,CODIGO2,DESCRIPCION CODIGOS DE CUATRO CARACTERES
0,A00,COLERA,A000,"COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO CH..."
1,A00,COLERA,A001,"COLERA DEBIDO A VIBRIO CHOLERAE O1, BIOTIPO EL..."
2,A00,COLERA,A009,COLERA NO ESPECIFICADO
3,A01,FIEBRES TIFOIDEA Y PARATIFOIDEA,A010,FIEBRE TIFOIDEA
4,A01,FIEBRES TIFOIDEA Y PARATIFOIDEA,A011,FIEBRE PARATIFOIDEA A

In [ ]:
enfermedades.to_excel("enfermedades_completado.xlsx", index=False)

Mapear los valores de cada celda

In [132]:
# Asegurar que los códigos estén limpios (sin espacios)
enfermedades['CODIGO2'] = enfermedades['CODIGO2'].astype(str).str.strip()
enfermedades['DESCRIPCION CODIGOS DE CUATRO CARACTERES'] = enfermedades['DESCRIPCION CODIGOS DE CUATRO CARACTERES'].astype(str)

In [133]:
# Diccionario que mapea código -> descripción
mapa_codigos = dict(zip(enfermedades['CODIGO2'], enfermedades['DESCRIPCION CODIGOS DE CUATRO CARACTERES']))

In [134]:
for col in columnas:
    col_desc = f'{col}_DESCRIPCION'
    data[col] = data[col].astype(str).str.strip()
    data[col_desc]= data[col].map(mapa_codigos)

### Análisis de datos faltantes

In [135]:
def resumen_datos(data):
    resumen = []
    total_filas = len(data)
    
    for col in data.columns:
        unicos = data[col].nunique()
        faltantes = data[col].isna().sum()
        ceros = (data[col] == 0).sum()
        porcentaje_faltante = (faltantes / total_filas) * 100
        super_10 = 'Sí' if porcentaje_faltante > 10 else 'No'
        
        resumen.append({
            'Columna': col,
            'Valores únicos': unicos,
            'Faltantes': faltantes,
            'Ceros': ceros,
            'Porcentaje de faltantes': porcentaje_faltante,
            'Más del 10% de faltantes': super_10
        })
    return pd.DataFrame(resumen)

In [136]:
tabla_resumen = resumen_datos(data)
display(HTML(tabla_resumen.to_html()))

### Variables a eliminar

In [ ]:
columnas_eliminar = ['CAUSA_666', 'CAUSA_667', 'C_DIR12', 'C_ANT22', 'C_ANT12', 'C_DIR12',
                     'C_MUERTEE', 'C_MUERTED', 'C_MUERTEC', 'C_MUERTEB', 'C_MCM1', 'C_ANT32', 
                     'C_PAT2', 'C_PAT1', 'C_ANT3', 'C_ANT2', 'C_ANT1', 'C_DIR1', 'C_MUERTE',
                     'CODPRES', 'IDADMISALUD', 'IDCLASADMI', 'filter_$', 'Year', 'C_BAS1', 'CONS_EXP',
                     'CODOCUR', 'CODMUNOC', 'CAUSA_MULT', 'IDPROFCER', 'QUINQ', 'CAU_HOMOL',
                     'SEXO', 'NOMBRE_ARCHIVO', 'perman_mun', 'PMAN_MUER', 'tiem_per', 'EST_CIVM', 'MAN_MUER',
                     'CODOCUR', 'CODMUNOC', 'C_MUERTE', 'ASIS_MED', 'OTRSITIODE', 'HORA', 'P_PMAN_IRIS',
                     'TIPOFORMULARIO', 'NIVEL_EDU', 'SIMUERTEPO', 'COD_INST', 'NOM_INST', 'CAUSA_666_DESCRIPCION',
                     'CAUSA_667_DESCRIPCION', 'C_MUERTEE_DESCRIPCION', 'C_MUERTED_DESCRIPCION',
                     'C_MUERTEC_DESCRIPCION', 'C_MUERTEB_DESCRIPCION', 'C_MCM1_DESCRIPCION', 'C_ANT32_DESCRIPCION',
                     'C_PAT2_DESCRIPCION', 'C_MUERTE_DESCRIPCION', 'SIMUERTE_POR_OCUPACION', 'EST_CIVIL', 'PROBABLE MANERA DE MUERTE']

for col in columnas_eliminar:
    if col in data.columns:
        del data[col]

In [138]:
data['SEG_SOCIAL'].unique()
data['SEGURIDAD SOCIAL'].unique()

array([nan, 'Subsidiado', 'Particular', 'Vinculado', 'Contributivo',
       'Sin información', 'Ignorado', 'Otro'], dtype=object)

In [56]:
data[['SEG_SOCIAL', 'SEGURIDAD SOCIAL']].head()

  SEG_SOCIAL SEGURIDAD SOCIAL
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN

In [139]:
display(HTML(data.head(10).to_html()))

In [222]:
data.shape

(58934, 35)

In [140]:
tabla_resumen = resumen_datos(data)
display(HTML(tabla_resumen.to_html()))

In [141]:
#Rellenar los departamentos faltantes

largo = len(data)
for i in range(largo):
    if pd.isna(data.loc[i, 'DEPARTAMENTO DE RESIDENCIA']):
        data.loc[i, 'DEPARTAMENTO DE RESIDENCIA'] = data.loc[i, 'DEPARTAMENTO']

#### Imputar municipio por capital de departamento

Para los departamentos de residencia faltantes se imputa por el mismo departamento de registro de defunción

In [142]:
capitales_departamentales = {
    'AMAZONAS': 'LETICIA',
    'ANTIOQUIA': 'MEDELLÍN',
    'ARAUCA': 'ARAUCA',
    'ATLÁNTICO': 'BARRANQUILLA',
    'BOLÍVAR': 'CARTAGENA DE INDIAS',
    'BOYACÁ': 'TUNJA',
    'CALDAS': 'MANIZALES',
    'CAQUETÁ': 'FLORENCIA',
    'CASANARE': 'YOPAL',
    'CAUCA': 'POPAYÁN',
    'CESAR': 'VALLEDUPAR',
    'CHOCÓ': 'QUIBDÓ',
    'CÓRDOBA': 'MONTERÍA',
    'CUNDINAMARCA': 'BOGOTÁ',
    'GUAINÍA': 'INÍRIDA',
    'GUAVIARE': 'SAN JOSÉ DEL GUAVIARE',
    'HUILA': 'NEIVA',
    'LA GUAJIRA': 'RIOHACHA',
    'MAGDALENA': 'SANTA MARTA',
    'META': 'VILLAVICENCIO',
    'NARIÑO': 'PASTO',
    'NORTE DE SANTANDER': 'CÚCUTA',
    'PUTUMAYO': 'MOCOA',
    'QUINDÍO': 'ARMENIA',
    'RISARALDA': 'PEREIRA',
    'SAN ANDRÉS Y PROVIDENCIA': 'SAN ANDRÉS',
    'SANTANDER': 'BUCARAMANGA',
    'SUCRE': 'SINCELEJO',
    'TOLIMA': 'IBAGUÉ',
    'VALLE DEL CAUCA': 'CALI',
    'VAUPÉS': 'MITÚ',
    'VICHADA': 'PUERTO CARREÑO',
    'BOGOTÁ, D.C.': 'BOGOTÁ D.C.',
    'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA': 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA'
}

In [143]:
# Definir la función de imputación
def imputar_municipio(row):
    municipio = row['MUNICIPIO']
    departamento = row['DEPARTAMENTO']
    if pd.isna(municipio) or municipio == '':
        return capitales_departamentales.get(departamento, municipio)
    return municipio

Se imputa el municipio de residencia por el mismo registrado en la defunción

In [144]:
data['MUNICIPIO'] = data.apply(imputar_municipio, axis=1)

In [145]:
for i in range(largo):
    if pd.isna(data.loc[i, 'MUNICIPIO DE RESIDENCIA']):
        data.loc[i, 'MUNICIPIO DE RESIDENCIA'] = data.loc[i, 'MUNICIPIO']

In [146]:
# Imputar área y sitio de defunción
for i in range(largo):
    if pd.isna(data.loc[i, 'AREA DE RESIDENCIA']):
        data.loc[i, 'AREA DE RESIDENCIA'] = data.loc[i, 'A_DEFUN']

#### Frecuencia de estado civil

In [ ]:
conteo_categorias = data['ESTADO_CIVIL'].value_counts()  

for categoria, cantidad in conteo_categorias.items():
    print(f'La categoría "{categoria}" tiene {cantidad} registros')

La categoría "Casado" tiene 14114 registros
La categoría "Unión Libre, divorciado, otro" tiene 11267 registros
La categoría "Soltero" tiene 11056 registros
La categoría "Viudo" tiene 9808 registros
La categoría "Sin información" tiene 6440 registros

### Analizar e imputar datos faltantes para variables escogidas

#### Estado civil

In [151]:
grupo = data.groupby(['GRUPO_ETARIO', 'AREA_DEFUN', 'DEPARTAMENTO', 'MUNICIPIO'])['ESTADO_CIVIL'].value_counts(normalize=True).unstack().fillna(0)
grupo.head(10)

ESTADO_CIVIL                                                 Casado  \
GRUPO_ETARIO AREA_DEFUN DEPARTAMENTO MUNICIPIO
15-19        RURAL      HUILA        ALGECIRAS             0.000000
             URBANA     ANTIOQUIA    MEDELLÍN              0.000000
                                     YARUMAL               0.000000
                        ATLÁNTICO    BARRANQUILLA          0.000000
                        BOGOTÁ, D.C. BOGOTÁ, D.C.          0.333333
                        BOLÍVAR      EL CARMEN DE BOLÍVAR  0.000000
                        CALDAS       ANSERMA               0.000000
                                     MANIZALES             0.000000
                        CAUCA        TIMBÍO                1.000000
                        NARIÑO       PASTO                 1.000000

ESTADO_CIVIL                                               Sin información  \
GRUPO_ETARIO AREA_DEFUN DEPARTAMENTO MUNICIPIO
15-19        RURAL      HUILA        ALGECIRAS                         0.0
             URBANA     ANTIOQUIA    MEDELLÍN                          0.0
                                     YARUMAL                           0.0
                        ATLÁNTICO    BARRANQUILLA                      0.0
                        BOGOTÁ, D.C. BOGOTÁ, D.C.                      0.0
                        BOLÍVAR      EL CARMEN DE BOLÍVAR              0.0
                        CALDAS       ANSERMA                           0.0
                                     MANIZALES                         0.0
                        CAUCA        TIMBÍO                            0.0
                        NARIÑO       PASTO                             0.0

ESTADO_CIVIL                                                Soltero  \
GRUPO_ETARIO AREA_DEFUN DEPARTAMENTO MUNICIPIO
15-19        RURAL      HUILA        ALGECIRAS             0.000000
             URBANA     ANTIOQUIA    MEDELLÍN              0.000000
                                     YARUMAL               0.000000
                        ATLÁNTICO    BARRANQUILLA          1.000000
                        BOGOTÁ, D.C. BOGOTÁ, D.C.          0.333333
                        BOLÍVAR      EL CARMEN DE BOLÍVAR  0.000000
                        CALDAS       ANSERMA               1.000000
                                     MANIZALES             1.000000
                        CAUCA        TIMBÍO                0.000000
                        NARIÑO       PASTO                 0.000000

ESTADO_CIVIL                                               Unión Libre, divorciado, otro  \
GRUPO_ETARIO AREA_DEFUN DEPARTAMENTO MUNICIPIO
15-19        RURAL      HUILA        ALGECIRAS                                       1.0
             URBANA     ANTIOQUIA    MEDELLÍN                                        1.0
                                     YARUMAL                                         1.0
                        ATLÁNTICO    BARRANQUILLA                                    0.0
                        BOGOTÁ, D.C. BOGOTÁ, D.C.                                    0.0
                        BOLÍVAR      EL CARMEN DE BOLÍVAR                            1.0
                        CALDAS       ANSERMA                                         0.0
                                     MANIZALES                                       0.0
                        CAUCA        TIMBÍO                                          0.0
                        NARIÑO       PASTO                                           0.0

ESTADO_CIVIL                                                  Viudo
GRUPO_ETARIO AREA_DEFUN DEPARTAMENTO MUNICIPIO
15-19        RURAL      HUILA        ALGECIRAS             0.000000
             URBANA     ANTIOQUIA    MEDELLÍN              0.000000
                                     YARUMAL               0.000000
                        ATLÁNTICO    BARRANQUILLA          0.000000
                        BOGOTÁ, D.C. BOGOTÁ, D.C.          0.333333
                        BOLÍVAR      EL CARMEN DE BOLÍVAR  0.000000
                        CALDAS       ANSERMA               0.000000
                                     MANIZALES             0.000000
                        CAUCA        TIMBÍO                0.000000
                        NARIÑO       PASTO                 0.000000

Identificar grupos con valores faltantes

In [149]:
sin_info = data[data['ESTADO_CIVIL'] == 'Sin información']
conteo_grupos = sin_info.groupby(['GRUPO_ETARIO', 'A_DEFUN', 'DEPARTAMENTO', 'MUNICIPIO']).size()
conteo_grupos

GRUPO_ETARIO      A_DEFUN  DEPARTAMENTO  MUNICIPIO
15-19             1        QUINDÍO       ARMENIA                1
                           SANTANDER     FLORIDABLANCA          1
20-24             1        BOGOTÁ, D.C.  BOGOTÁ D.C.            1
                                         BOGOTÁ, D.C.           1
                           BOLÍVAR       CARTAGENA DE INDIAS    1
                                                               ..
Edad desconocida  3        CAQUETÁ       FLORENCIA              1
                           NARIÑO        PASTO                  2
                           PUTUMAYO      MOCOA                  1
                           SANTANDER     BUCARAMANGA            1
                           TOLIMA        IBAGUÉ                 1
Length: 1702, dtype: int64

In [231]:
data_filtrada = data[data['ESTADO_CIVIL'] != 'Sin información'].copy()

In [233]:
def obtener_moda(x):
    moda = x.mode()
    return moda.iloc[0] if not moda.empty else np.nan

moda_por_grupo = data_filtrada.groupby(['GRUPO_ETARIO', 'AREA_DEFUN', 'DEPARTAMENTO', 'MUNICIPIO'])['ESTADO_CIVIL'].agg(obtener_moda)

In [241]:
# Función para imputar
def imputar_estado_civil_moda(row):
    if row['ESTADO_CIVIL'] == 'Sin información':
        clave = (row['GRUPO_ETARIO'], row['A_DEFUN'], row['DEPARTAMENTO'], row['MUNICIPIO'])
        imputado = moda_por_grupo.get(clave, np.nan)
        return imputado if pd.notna(imputado) else 'Soltero'  # valor por defecto si no hay moda
    else:
        return row['ESTADO_CIVIL']

In [242]:
data['ESTADO_CIVIL_IMPUTADO_MODA'] = data.apply(imputar_estado_civil_moda, axis=1)

In [243]:
sin_info_original = data[data['ESTADO_CIVIL'] == 'Sin información'].head()
imputados_moda = data[data['ESTADO_CIVIL'] == 'Sin información'][['GRUPO_ETARIO', 'A_DEFUN', 'DEPARTAMENTO', 'MUNICIPIO', 'ESTADO_CIVIL_IMPUTADO_MODA']].head()

In [244]:
print("\n--- Primeros registros con 'Sin información' (original) ---")
print(sin_info_original[['GRUPO_ETARIO', 'A_DEFUN', 'DEPARTAMENTO', 'MUNICIPIO', 'ESTADO_CIVIL']].head())

print("\n--- Primeros registros con imputación por moda ---")
print(imputados_moda)

--- Primeros registros con 'Sin información' (original) ---
        GRUPO_ETARIO A_DEFUN  DEPARTAMENTO      MUNICIPIO     ESTADO_CIVIL
23  Edad desconocida       2         HUILA    SAN AGUSTÍN  Sin información
39             35-39       1          META  VILLAVICENCIO  Sin información
64             25-29       1         HUILA          NEIVA  Sin información
69             40-44       1       CAQUETÁ      FLORENCIA  Sin información
83             35-39       1  CUNDINAMARCA         SOACHA  Sin información

--- Primeros registros con imputación por moda ---
        GRUPO_ETARIO A_DEFUN  DEPARTAMENTO      MUNICIPIO  \
23  Edad desconocida       2         HUILA    SAN AGUSTÍN
39             35-39       1          META  VILLAVICENCIO
64             25-29       1         HUILA          NEIVA
69             40-44       1       CAQUETÁ      FLORENCIA
83             35-39       1  CUNDINAMARCA         SOACHA

   ESTADO_CIVIL_IMPUTADO_MODA
23                    Soltero
39                    Soltero
64                    Soltero
69                    Soltero
83                    Soltero

In [245]:
conteo_categorias = data['ESTADO_CIVIL_IMPUTADO_MODA'].value_counts()  

for categoria, cantidad in conteo_categorias.items():
    print(f'La categoría "{categoria}" tiene {cantidad} registros')

La categoría "Soltero" tiene 17496 registros
La categoría "Casado" tiene 14114 registros
La categoría "Unión Libre, divorciado, otro" tiene 11267 registros
La categoría "Viudo" tiene 9808 registros

In [ ]:
data['ESTADO_CIVIL_IMPUTADO_MODA'].isna().sum()

6249

#### Imputar datos NaN de estado civil por proporción

In [307]:
# Distribución conocida (sin valores faltantes)
estado_civil_counts = data['ESTADO_CIVIL_IMPUTADO_MODA'].value_counts()
total_known = estado_civil_counts.sum()

# Calcular proporciones
proporciones = estado_civil_counts / total_known

# Cantidad de valores faltantes
n_missing = data['ESTADO_CIVIL_IMPUTADO_MODA'].isna().sum()

# Determinar cuántos valores imputar por categoría
asignaciones = (proporciones * n_missing).round().astype(int)

In [308]:
# Ajustar si hay diferencia por redondeo
diferencia = n_missing - asignaciones.sum()
if diferencia != 0:
    # Ajustar a la categoría más frecuente
    categoria_max = asignaciones.idxmax()
    asignaciones[categoria_max] += diferencia

# Obtener los índices faltantes y barajarlos
missing_indices = data[data['ESTADO_CIVIL_IMPUTADO_MODA'].isna()].index
np.random.seed(42)
shuffled_indices = np.random.permutation(missing_indices)

In [309]:
# Imputar valores de forma aleatoria y proporcional
start = 0
for categoria, cantidad in asignaciones.items():
    end = start + cantidad
    indices_para_categoria = shuffled_indices[start:end]
    data.loc[indices_para_categoria, 'ESTADO_CIVIL_IMPUTADO_MODA'] = categoria
    start = end

In [310]:
# Ahora asignamos esta columna imputada a la original
data['ESTADO_CIVIL'] = data['ESTADO_CIVIL_IMPUTADO_MODA']

# Verificamos que ya no haya valores faltantes
print(data['ESTADO_CIVIL'].isna().sum())

0

#### Inspeccionar Área de residencia

In [271]:
counts = data['AREA_RES'].value_counts()
counts

AREA_RES
1    42514
      7542
2     7223
3     1651
"        4
Name: count, dtype: int64

In [272]:
counts = data['AREA DE RESIDENCIA'].value_counts()
counts

AREA DE RESIDENCIA
Cabecera municipal                                      42514
Centro poblado (Inspección, corregimiento o caserío)     7223
1                                                        6827
Rural disperso                                           1651
2                                                         644
3                                                          75
Name: count, dtype: int64

In [ ]:
data['AREA DE RESIDENCIA'] = data['AREA DE RESIDENCIA'].replace({'1': 'Sin informacion', '2': 'Sin informacion', '3': 'Sin informacion'})

counts = data['AREA DE RESIDENCIA'].value_counts()
print(counts)

AREA DE RESIDENCIA
Cabecera municipal                                      42514
Sin informacion                                          7546
Centro poblado (Inspección, corregimiento o caserío)     7223
Rural disperso                                           1651
Name: count, dtype: int64

Se va a trasladar ponderadamente los datos de la categoría sin información a las otras categorías

In [274]:
counts = data['AREA_DEFUN'].value_counts()
counts

AREA_DEFUN
URBANA             53701
RURAL               4498
SIN INFORMACIÓN      735
Name: count, dtype: int64

In [281]:
# Calcular proporciones actuales
counts = data['AREA_DEFUN'].value_counts()
total_known = counts['URBANA'] + counts['RURAL']
p_urbana = counts['URBANA'] / total_known
p_rural = counts['RURAL'] / total_known

In [282]:
# Cantidad de 'SIN INFORMACIÓN'
sin_info_count = counts.get('SIN INFORMACIÓN', 0)

In [283]:
# Calcular cuántos asignar a cada clase
n_urbana = int(round(sin_info_count * p_urbana))
n_rural = sin_info_count - n_urbana  # El resto

In [284]:
# Obtener índices de filas con 'SIN INFORMACIÓN'
sin_info_indices = data[data['AREA_DEFUN'] == 'SIN INFORMACIÓN'].index

# Barajar índices para asignar aleatoriamente
np.random.seed(42)  # Semilla para reproducibilidad
shuffled_indices = np.random.permutation(sin_info_indices)

In [285]:
# Asignar valores nuevos
data.loc[shuffled_indices[:n_urbana], 'AREA_DEFUN'] = 'URBANA'
data.loc[shuffled_indices[n_urbana:], 'AREA_DEFUN'] = 'RURAL'

In [286]:
# Verificar nuevo conteo
print(data['AREA_DEFUN'].value_counts())

AREA_DEFUN
URBANA    54379
RURAL      4555
Name: count, dtype: int64

Imputación para la categoría `Sin información` de `área de residencia`

Se realizó una reclasificación de los registros con valor 'Sin informacion' en la variable AREA DE RESIDENCIA, utilizando como referencia la variable AREA_DEFUN. Para los casos en que AREA_DEFUN era 'URBANA', se asignó directamente la categoría 'Cabecera municipal'. Para los casos con AREA_DEFUN igual a 'RURAL', se redistribuyeron proporcionalmente entre 'Centro poblado (Inspección, corregimiento o caserío)' y 'Rural disperso', según la frecuencia observada de estas categorías en los datos. Con este procedimiento se eliminó la categoría ambigua, mejorando la calidad y precisión de la variable AREA DE RESIDENCIA.

In [296]:
# Frecuencias de las opciones rurales conocidas
rural_counts = data['AREA DE RESIDENCIA'].value_counts()
centro_poblado = rural_counts['Centro poblado (Inspección, corregimiento o caserío)']
rural_disperso = rural_counts['Rural disperso']
total_rural = centro_poblado + rural_disperso

In [297]:
p_centro = centro_poblado / total_rural
p_disperso = rural_disperso / total_rural

# Filtrar solo las filas con 'Sin informacion' en AREA DE RESIDENCIA
sin_info_mask = data['AREA DE RESIDENCIA'] == 'Sin informacion'
sin_info_indices = data[sin_info_mask].index

In [300]:
np.random.seed(42) 

for idx in sin_info_indices:
    if data.at[idx, 'AREA_DEFUN'] == 'URBANA':
        data.at[idx, 'AREA DE RESIDENCIA'] = 'Cabecera municipal'
    else:  # RURAL
        # Asignar aleatoriamente según proporciones
        data.at[idx, 'AREA DE RESIDENCIA'] = np.random.choice(
            ['Centro poblado (Inspección, corregimiento o caserío)', 'Rural disperso'],
            p=[p_centro, p_disperso]
        )

In [301]:
print(data['AREA DE RESIDENCIA'].value_counts())

AREA DE RESIDENCIA
Cabecera municipal                                      49411
Centro poblado (Inspección, corregimiento o caserío)     7749
Rural disperso                                           1774
Name: count, dtype: int64

#### Inspeccionar ``Seguridad Social``

In [287]:
conteo_categorias = data['SEGURIDAD SOCIAL'].value_counts()
for categoria, cantidad in conteo_categorias.items():
    print(f'La categoría "{categoria}" tiene {cantidad} registros')

La categoría "Subsidiado" tiene 24005 registros
La categoría "Contributivo" tiene 13058 registros
La categoría "Vinculado" tiene 4081 registros
La categoría "Otro" tiene 1418 registros
La categoría "Particular" tiene 910 registros

In [288]:
categorias_a_cambiar = ['Sin información', 'Ignorado']
categoria_destino = ['Otro']

In [289]:
for categoria in categorias_a_cambiar:
    data.loc[data['SEGURIDAD SOCIAL'] == categoria, 'SEGURIDAD SOCIAL'] = categoria_destino[0]

In [290]:
conteo_categorias_actualizado = data['SEGURIDAD SOCIAL'].value_counts()
print("\n--- Conteo de categorías después de la reclasificación ---")
for categoria, cantidad in conteo_categorias_actualizado.items():
    print(f'La categoría "{categoria}" tiene {cantidad} registros')

--- Conteo de categorías después de la reclasificación ---
La categoría "Subsidiado" tiene 24005 registros
La categoría "Contributivo" tiene 13058 registros
La categoría "Vinculado" tiene 4081 registros
La categoría "Otro" tiene 1418 registros
La categoría "Particular" tiene 910 registros

In [ ]:
data['SEGURIDAD SOCIAL'].isna().sum()

15462

In [ ]:
df_train = data[data['SEGURIDAD SOCIAL'].notna()].copy()
df_pred = data[data['SEGURIDAD SOCIAL'].isna()].copy()

# Variables predictoras
features = ['MUNICIPIO DE RESIDENCIA', 'ESTADO_CIVIL', 'GRUPO_ETARIO']

In [ ]:
# Codificar las variables categóricas
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_train = encoder.fit_transform(df_train[features])
X_pred = encoder.transform(df_pred[features])

# Variable objetivo
y_train = df_train['SEGURIDAD SOCIAL']

In [ ]:
# Modelo
model = RandomForestClassifier(random_state=42, n_estimators=100)
model.fit(X_train, y_train)

# Predecir los valores faltantes
y_pred = model.predict(X_pred)

In [ ]:
# Asignar predicciones a las filas faltantes
data.loc[df_pred.index, 'SEGURIDAD SOCIAL'] = y_pred

In [ ]:

# Validar que no haya valores faltantes
print(data['SEGURIDAD SOCIAL'].isna().sum())

0

Métricas del modelo para la imputación

In [ ]:
# Realizar predicciones en los datos de entrenamiento para evaluar el modelo
y_train_pred = model.predict(X_train)

In [ ]:
# Calcular las métricas
accuracy = accuracy_score(y_train, y_train_pred)
f1 = f1_score(y_train, y_train_pred, average='weighted')  # Promedio ponderado para manejar clases desbalanceadas
precision = precision_score(y_train, y_train_pred, average='weighted')
recall = recall_score(y_train, y_train_pred, average='weighted')
conf_matrix = confusion_matrix(y_train, y_train_pred)

# Imprimir las métricas
print(f"Accuracy: {accuracy:.4f}")
print(f"F1-Score (weighted): {f1:.4f}")
print(f"Precision (weighted): {precision:.4f}")
print(f"Recall (weighted): {recall:.4f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.6789
F1-Score (weighted): 0.6626
Precision (weighted): 0.6861
Recall (weighted): 0.6789
Confusion Matrix:
[[ 7671    23    23  5218   123]
 [  388   329     4   670    27]
 [  215     8   243   418    26]
 [ 3776    30    23 19989   187]
 [  940    15    13  1831  1282]]

In [315]:
conteo_categorias_actualizado = data['SEGURIDAD SOCIAL'].value_counts()
print("\n--- Conteo de categorías después de la reclasificación ---")
for categoria, cantidad in conteo_categorias_actualizado.items():
    print(f'La categoría "{categoria}" tiene {cantidad} registros')

--- Conteo de categorías después de la reclasificación ---
La categoría "Subsidiado" tiene 32552 registros
La categoría "Contributivo" tiene 18948 registros
La categoría "Vinculado" tiene 4793 registros
La categoría "Otro" tiene 1594 registros
La categoría "Particular" tiene 1047 registros

#### Tratamiento de la variable etnia

In [317]:
for cat in data['ETNIA'].unique():
    print(f'La categoría "{cat}" tiene {data[data["ETNIA"] == cat].shape[0]} registros')

La categoría "nan" tiene 0 registros
La categoría "Sin información" tiene 1147 registros
La categoría "Ninguno de las anteriores" tiene 24150 registros
La categoría "Negro(a), mulato(a), afrocolombiano(a) o afrodescendiente" tiene 1248 registros
La categoría "Indígena" tiene 587 registros
La categoría "Rom (Gitano)" tiene 17 registros
La categoría "Raizal del archipielago de San Andres y Providencia" tiene 22 registros
La categoría "Palenquero de San Basilio" tiene 6 registros

In [318]:
data['ETNIA'].isna().sum()

31757

In [319]:
data['ETNIA'] = data['ETNIA'].replace({'Sin información': 'Ninguno de las anteriores', 'Ignorado': 'Ninguno de las anteriores'})
data['ETNIA'] = data['ETNIA'].fillna('Ninguno de las anteriores')

#### Inspección de variable `NIVEL EDUCATIVO`

In [324]:
conteo = data['NIVEL_EDUCACION'].value_counts()
conteo

NIVEL_EDUCACION
Primaria           19382
Secundaria          7519
Ninguno             5230
Superior            1948
Sin información      470
Preescolar           405
Name: count, dtype: int64

In [325]:
data['NIVEL_EDUCACION'].isna().sum()

23980

In [330]:
data['NIVEL_EDUCACION'] = data['NIVEL_EDUCACION'].replace('Sin información', 'Ninguno')

In [332]:
df_train = data[data['NIVEL_EDUCACION'].notna()].copy()
df_pred = data[data['NIVEL_EDUCACION'].isna()].copy()

features = ['MUNICIPIO DE RESIDENCIA', 'ESTADO_CIVIL', 'GRUPO_ETARIO',
            'SEGURIDAD SOCIAL', 'OCUPACION', 'AREA DE RESIDENCIA']

In [334]:
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_train = encoder.fit_transform(df_train[features])
X_pred = encoder.transform(df_pred[features])

y_train = df_train['NIVEL_EDUCACION']

In [335]:
model_educ = RandomForestClassifier(n_estimators=100, random_state=42)
model_educ.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [336]:
y_train_pred = model_educ.predict(X_train)
print("Evaluación del modelo en el conjunto conocido:")
print(classification_report(y_train, y_train_pred))

Evaluación del modelo en el conjunto conocido:
              precision    recall  f1-score   support

     Ninguno       0.91      0.75      0.83      5700
  Preescolar       0.93      0.63      0.75       405
    Primaria       0.83      0.95      0.88     19382
  Secundaria       0.82      0.70      0.76      7519
    Superior       0.89      0.61      0.73      1948

    accuracy                           0.84     34954
   macro avg       0.88      0.73      0.79     34954
weighted avg       0.84      0.84      0.84     34954

In [337]:
y_pred = model_educ.predict(X_pred)
data.loc[df_pred.index, 'NIVEL_EDUCACION'] = y_pred

In [338]:
print("\n¿Valores faltantes después de la imputación?:", data['NIVEL_EDUCACION'].isna().sum())

¿Valores faltantes después de la imputación?: 0

In [339]:
conteo = data['NIVEL_EDUCACION'].value_counts()
conteo

NIVEL_EDUCACION
Primaria      35764
Secundaria    11485
Ninguno        8675
Superior       2540
Preescolar      470
Name: count, dtype: int64

#### Inspección de grupo etario

In [341]:
conteo = data['GRUPO_ETARIO'].value_counts()
conteo

GRUPO_ETARIO
50-54               6488
55-59               6343
60-64               6225
45-49               5956
65-69               5717
40-44               5016
70-74               4972
75-79               4288
35-39               3621
80-84               3151
85 y más            2734
30-34               2064
Edad desconocida    1084
25-29                722
20-24                159
15-19                 22
Name: count, dtype: int64

Asignar Edad desconocida por ponderación a las demás categorías

In [342]:
grupo_etario_counts = data['GRUPO_ETARIO'].value_counts()

# Separar "Edad desconocida" y el total sin ella
edad_desconocida = grupo_etario_counts.get("Edad desconocida", 0)
grupo_etario_sin_desconocida = grupo_etario_counts.drop("Edad desconocida")

In [343]:
# Calcular proporciones
proporciones = grupo_etario_sin_desconocida / grupo_etario_sin_desconocida.sum()

# Calcular cuántos registros se deben asignar a cada grupo
asignaciones = (proporciones * edad_desconocida).round().astype(int)

In [344]:
# Crear un diccionario para reasignar
asignacion_dict = asignaciones.to_dict()

# Filtrar los registros con "Edad desconocida"
mask_desconocida = data['GRUPO_ETARIO'] == "Edad desconocida"
df_desconocida = data[mask_desconocida].copy()

In [345]:
# Reasignar proporcionalmente
data.loc[mask_desconocida, 'GRUPO_ETARIO'] = np.random.choice(
    list(asignacion_dict.keys()),
    size=len(df_desconocida),
    p=proporciones.values
)

# Verificar que ya no hay "Edad desconocida"
print(data['GRUPO_ETARIO'].value_counts())

GRUPO_ETARIO
50-54       6612
55-59       6453
60-64       6360
45-49       6049
65-69       5840
40-44       5099
70-74       5065
75-79       4371
35-39       3702
80-84       3218
85 y más    2779
30-34       2094
25-29        735
20-24        163
15-19         22
Name: count, dtype: int64

Imputar por proporción los valores faltantes

In [347]:
# Distribución de valores no nulos
distribucion = data['GRUPO_ETARIO'].value_counts(normalize=True)

# Índices de los NaN
faltantes_idx = data[data['GRUPO_ETARIO'].isna()].index

In [348]:
# Imputar valores faltantes proporcionalmente
data.loc[faltantes_idx, 'GRUPO_ETARIO'] = np.random.choice(
    distribucion.index,
    size=len(faltantes_idx),
    p=distribucion.values
)

In [ ]:
print("Faltantes después de imputación:", data['GRUPO_ETARIO'].isna().sum())

Faltantes después de imputación: 0

### Datos finales posterior a imputación

In [360]:
tabla_resumen = resumen_datos(data)
display(HTML(tabla_resumen.to_html()))

### Eliminar columnas no reelevantes para el estudio y anexión de datos socio-demográficos

#### Eliminar variables no reelevantes

In [365]:
variables_eliminar = ['CODPTORE', 'CODMUNRE', 'AREA_RES', 'SEG_SOCIAL', 'IDPERTET',
                      'COD_MUNIC_RESIDENCIA_CORREGIDO', 'A_DEFUN', 'SIT_DEFUN', 'OCUPACION', 
                      'ASISTENCIA MEDICA PREVIO A MUERTE', 'ESTADO_CIVIL_IMPUTADO_MODA', 'C_ANT12_DESCRIPCION',
                      'C_ANT22_DESCRIPCION', 'C_DIR12_DESCRIPCION']

for col in variables_eliminar:
    if col in data.columns:
        del data[col]

Imputar con 'No patología' a las comorbilidades

In [367]:
columnas = [
    'C_PAT1_DESCRIPCION', 'C_ANT3_DESCRIPCION', 'C_ANT2_DESCRIPCION',
    'C_ANT1_DESCRIPCION', 'C_DIR1_DESCRIPCION'
]

# Imputar valores faltantes con "No patología"
for col in columnas:
    data[col] = data[col].fillna("No patología")

In [378]:
data.rename(columns={'ANO': 'AÑO'}, inplace=True)
display(HTML(data.head(6).to_html()))

#### Anexar datos socio-demográficos y económicos

Agregar inicialmente los datos de población mujeres anual

In [370]:
poblacion_mujeres.head()

   DP   AÑO  Total Mujeres
0   5  1985        2017630
1   5  1986        2060423
2   5  1987        2104203
3   5  1988        2148202
4   5  1989        2191845

Codificar departamento con el códifo DIVIPOLA

In [372]:
tipo= poblacion_mujeres['DP'].dtype
print('El tipo de datos es: ', tipo)
if poblacion_mujeres['DP'].dtype == 'int64':
    poblacion_mujeres['DP'] = poblacion_mujeres['DP'].astype(str)
    print(f'Y dado que era {tipo} , se convirtió a string')
    poblacion_mujeres['DEPARTAMENTO'] = poblacion_mujeres['DP'].map(map_dpto)
    print(poblacion_mujeres['DEPARTAMENTO'].unique())
else:
    poblacion_mujeres['DEPARTAMENTO'] = poblacion_mujeres['DP'].map(map_dpto)
    print(poblacion_mujeres['DEPARTAMENTO'].unique())

El tipo de datos es:  int64
Y dado que era int64 , se convirtió a string
['ANTIOQUIA' 'ATLÁNTICO' 'BOGOTÁ, D.C.' 'BOLÍVAR' 'BOYACÁ' 'CALDAS'
 'CAQUETÁ' 'CAUCA' 'CESAR' 'CÓRDOBA' 'CUNDINAMARCA' 'CHOCÓ' 'HUILA'
 'LA GUAJIRA' 'MAGDALENA' 'META' 'NARIÑO' 'NORTE DE SANTANDER' 'QUINDÍO'
 'RISARALDA' 'SANTANDER' 'SUCRE' 'TOLIMA' 'VALLE DEL CAUCA' 'ARAUCA'
 'CASANARE' 'PUTUMAYO'
 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA' 'AMAZONAS'
 'GUAINÍA' 'GUAVIARE' 'VAUPÉS' 'VICHADA']

In [373]:
poblacion_mujeres.head()

  DP   AÑO  Total Mujeres DEPARTAMENTO
0  5  1985        2017630    ANTIOQUIA
1  5  1986        2060423    ANTIOQUIA
2  5  1987        2104203    ANTIOQUIA
3  5  1988        2148202    ANTIOQUIA
4  5  1989        2191845    ANTIOQUIA

Unimos la población

In [376]:
data['ANO'] = data['AÑO'].astype(int)
data['DEPARTAMENTO'] = data['DEPARTAMENTO'].str.upper()

poblacion_mujeres['AÑO'] = poblacion_mujeres['AÑO'].astype(int)
poblacion_mujeres['DEPARTAMENTO'] = poblacion_mujeres['DEPARTAMENTO'].str.upper()

In [377]:
# Realizamos el merge
data = data.merge(poblacion_mujeres[['AÑO', 'DEPARTAMENTO', 'Total Mujeres']], 
                  on=['AÑO', 'DEPARTAMENTO'], 
                  how='left')

In [380]:
output_path = os.path.join(data_path, 'data_final.xlsx')

# Guardar como Excel
data.to_excel(output_path, index=False, engine='openpyxl')
print(f'Data saved to {output_path}')

Data saved to C:/Users/henry/Documents/jbook/Cacervix/datos/data_final.xlsx